### PR TITLE
ci: website preview workflow

### PR DESCRIPTION
**Pull request by jooola**
Once this is merged, a member of LibreTime can trigger a website preview deployment by commenting the pull request with the command **/deploy-website**. To clean the deployment, you need to close the pull request.

### CODE REVIEW

**Comment by jooola** [comment]
Here is test pull request I used: https://github.com/jooola/libretime/pull/79

**Comment by paddatrapper** [comment]
LGTM, though it seems like the preview didn't correctly use the URL defined in the workflow in your example PR?

Also is it possible to automatically clean up on PR close? I can see us forgetting to run /clean-website

**Comment by jooola** [comment]
Yes, something is off with the checkout command. I'll do some more testing.

**Comment by jooola** [comment]
Ok finally got it working !

**Pull request merged**
