### PR TITLE
chore: add test-stream-input tool 

### PR DESCRIPTION
**Pull request by jooola**
This helps sending a sine wave sound to the input harbor for testing purpose. I know ffmpeg more reliable than butt or mixx.

### CODE REVIEW

**Comment by paddatrapper** [comment]
Do we want docs on how to use this?

**Comment by jooola** [comment]
Yeah, you're probably right. I'll do this.

**Comment by jooola** [comment]
This should give plenty of documentation:
```
./tools/test-stream-input.py --help
```

**Comment by paddatrapper** [comment]
Is this something that should be added to any troubleshooting documentation?

**Comment by jooola** [comment]
image

**Pull request merged**
