### PR TITLE
Update Calendar Manual

### PR DESCRIPTION
**Pull request by paddatrapper**
Part of a drive to update the manual to reflect the current status of LibreTime. This updates the Calendar section of the manual.

### CODE REVIEW

**Comment by Robbt** [comment]
This looks great. Thanks for taking the time to do this. The only question I have is about the removal of Cancel Current Show. On my version of LibreTime this is still the dialog box that pops up and I don't think we currently are supporting the recording of shows at this point.

**Comment by paddatrapper** [comment]
I just checked mine and it has the same. The show I was testing must have had recording enabled (though no recorded file was produced, not sure if that was because of the lack of a physical line in or if it isn't set-up/supported). I'll fix that section later today

**Comment by paddatrapper** [comment]
Fixed

**Comment by hairmare** [comment]
Awesome guys! Nice work!

**Pull request merged**
