### PR TITLE
mostly run analyzer tests on travis

### PR DESCRIPTION
**Pull request by hairmare**
* [x] regonfigured the build matrix with more php jobs and a separate python job (we can add more python jobs later)
* [x] run tests on travis' trusty beta container (it's closer to what we need anyway)
* [x] install packages needed for analyzer tests in build env
* [x] added docs on how to run nosetests locally
* [x] don't run initctl in analyzer setup so setup can also be used on travis (and add it to the install script directly)
* [x] ignore replaygain checks on travis (it has proven quite impossible to get the needed python-gi module to work in the provided virtualenv)
* [x] make sure conditional tests don't kill the build (! return status instead of X)

I tried a lot of solutions to get the replaygain checks to run. I needed to decide that this has gone far enough, maybe someone who is more of a pythonista than me can take a crack at it and get it solved. Even without running those tests on CI/CD there are still plenty others.

This PR only has parts of what are needed for getting python tests running on travis as per #15. I only took a quick shot at anything not analyzer and figured I would not be able to "fix" them without digging a bit deeper (ie. also getting rid of std_err_override).

### CODE REVIEW

**Comment by hairmare** [comment]
I noticed a snag, the failing test is showing up as ! and not as X, I'm sorting that out as I type.

**Comment by Robbt** [comment]
Ok, so I started testing this. I realized I needed to type ./travis/python.sh to run the travis tests.
And I ran into 
Building docs...
+ mkdocs build --clean -q
./travis/python.sh: line 13: mkdocs: command not found

So I'm figuring there is something missing. I re-ran the install and it didn't add mkdocs. 

Also wasn't sure what is going on with the Merge branch 'master' into feature/analyzer-on-travis commit. It looks like it is touching a lot of stuff not specifically mentioned here. 

If that is intentional and this PR is just supposed to fix the travis python tests then I can go ahead and commit it as that appears to be working.

**Comment by Robbt** [comment]
Ok, I noticed the docs directory with documentation.md with instructions on how to install mkdocs. Do we want to do that by default or test to see if docs are included or just add a footnote for how to install mkdocs to the python.sh ? 

Either way I think this is ready for commit once we make a decision on whether to fix this now or later.

**Comment by hairmare** [comment]
`mkdocs` gets installed on travis by [master/.travis.yml#L14](https://github.com/LibreTime/libretime/blob/master/.travis.yml#L14). `travis/python.sh` is really only for travis.

Normally you should not need to run it locally, to run tests the recommended way is still `cd airtime_mvc/tests && ../../vendor/bin/phpunit` as per http://libretime.org/testing/. 

I'd rather not add it to the installer since mkdocs is not needed during runtime. The Vagrant setup from #20 will also help working with the docs.

**Pull request merged**
