### PR TITLE
feat: rewrite legacy migrations to django migration

### LINKED ISSUE #1377: Some migrations are broken on fresh install
**Describe the bug**

On fresh installs, the first logs for zend are from error raised in the `application/upgrade/Upgrades.php`.

It looks like some migrations does not run properly and the errors aren't logged properly.

**To Reproduce**

1. On a fresh install
2. Run the setup form
3. Check the logs

**Expected behavior**

We should have errors in the logs. This might be related to #1300 

**LibreTime version:** main branch the 2021 10 05

**Installation method:** Vagrant up
- OS: buster/bullseye
- Method: ./install -fap

**Additional context**

```
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:26 - errorAction()] - Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:27 - errorAction()] - #0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-view/library/Zend/View/Helper/Json.php(87): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(73): Zend_View_Helper_Json->json()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(102): Zend_Controller_Action_Helper_Json->encodeJson()
#4 /vagrant/airtime_mvc/application/controllers/ApiController.php(122): Zend_Controller_Action_Helper_Json->sendJson()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->versionAction()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#8 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#9 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#10 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#11 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#12 {main}
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243 in /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php:323
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-view/library/Zend/View/Helper/Json.php(87): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(73): Zend_View_Helper_Json->json()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/Json.php(102): Zend_Controller_Action_Helper_Json->encodeJson()
#4 /vagrant/airtime_mvc/application/controllers/ApiController.php(122): Zend_Controller_Action_Helper_Json->sendJson()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->versionAction()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#8 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#9 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#10 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#11 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#12 {main}
2021-10-05T15:34:27+00:00 WARN (4): Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243)
2021-10-05T15:34:27+00:00 ERR (3): localhost [Logging.php:165 - loggingShutdownCallback()] - Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#4 {main}
  thrown at /vagrant/airtime_mvc/application/airtime-boot.php:93
array (
  'type' => 1,
  'message' => 'Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once(\'/vagrant/airtim...\')
#4 {main}
  thrown',
  'file' => '/vagrant/airtime_mvc/application/airtime-boot.php',
  'line' => 93,
)
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:26 - errorAction()] - Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:27 - errorAction()] - #0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ContextSwitch.php(283): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/application/controllers/ApiController.php(80): Zend_Controller_Action_Helper_ContextSwitch->initContext()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(133): ApiController->init()
#4 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#8 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#10 {main}
2021-10-05T15:34:27+00:00 ERR (3): localhost [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Response_Exception: Cannot send headers; headers already sent in /vagrant/airtime_mvc/application/upgrade/Upgrades.php, line 243 in /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php:323
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders()
#1 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action/Helper/ContextSwitch.php(283): Zend_Controller_Response_Abstract->setHeader()
#2 /vagrant/airtime_mvc/application/controllers/ApiController.php(80): Zend_Controller_Action_Helper_ContextSwitch->initContext()
#3 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(133): ApiController->init()
#4 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct()
#5 /vagrant/airtime_mvc/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#6 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /vagrant/airtime_mvc/vendor/zf1s/zend-application/library/Zend/Application.php(391): Zend_Application_Bootstrap_Bootstrap->run()
#8 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#10 {main}
2021-10-05T15:34:27+00:00 WARN (4): Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243)
2021-10-05T15:34:27+00:00 ERR (3): localhost [Logging.php:165 - loggingShutdownCallback()] - Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#4 {main}
  thrown at /vagrant/airtime_mvc/application/airtime-boot.php:93
array (
  'type' => 1,
  'message' => 'Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /vagrant/airtime_mvc/application/upgrade/Upgrades.php:243) in /vagrant/airtime_mvc/application/airtime-boot.php:93
Stack trace:
#0 /vagrant/airtime_mvc/vendor/zf1s/zend-log/library/Zend/Log.php(636): exception_error_handler()
#1 [internal function]: Zend_Log->errorHandler()
#2 /vagrant/airtime_mvc/application/airtime-boot.php(93): header()
#3 /vagrant/airtime_mvc/public/index.php(68): require_once(\'/vagrant/airtim...\')
#4 {main}
  thrown',
  'file' => '/vagrant/airtime_mvc/application/airtime-boot.php',
  'line' => 93,
)
```

### PR DESCRIPTION
**Pull request by jooola**
Depends on #1626 

A rewrite of the migrations previously managed by the legacy upgrade controller.

Fixes #1377

### CODE REVIEW

**Comment by jooola** [comment]
I am facing a problem where we need to choose how we want to proceed.

- The `libretime-api migrate` command (actually the entire CLI) requires the configuration file to be present so we have the database configuration.
- The web installer rely on the fact that the config file exists to determine if the installation is done or not.
- The initial storage directory needs to be set or the UI will fail miserably (setup schema + default data, but not storage path).

I feel like replacing the entire web installer makes this PR somewhat huge, as I will have to find a way to configure those storage settings, along with the icecast admin password and the public url for cors settings.

I am tempted to move the storage setting, public URL to the configuration file, but I don't know if the we are ready to do the change ?
We could keep the web installer for the time being, but I feel uncomfortable playing around the web installer to make it work with the new migrations / setup system.

So we probably will have to replace the php migration system and the web installer in a this single PR, so we don't build to much temporary stuff around.

I wonder what your thoughts are @paddatrapper

**Comment by paddatrapper** [comment]
We already run the Django migrations from the web installer at the same point as the PHP ones. So why not remove the PHP migration call and add an additional Django migration call in the upgrade logic so that we handle #1487? That way the web installer doesn't need changing much and the chicken and egg problem is avoided.

**Comment by jooola** [comment]
I think we should drop the web installer. The problem I see with your solution is that we put a hard dependency between legacy and the api. We don't want that as it will be a mess for the docker images for example.

**Comment by paddatrapper** [comment]
Docker requires the config file mounted, so it doesn't use the Web installer anyway. The solution there will be different and mostly scripted into the startup scripts

**Comment by jooola** [comment]
Closing in favor of #1821

**Pull request closed without merging**
