### PR TITLE
chore: add semantic-release prefix to dependabot commits

### PR DESCRIPTION
**Pull request by paddatrapper**
Not strictly necessary yet, but will make it fit in with #1180 when we get there

### CODE REVIEW

**Comment by jooola** [comment]
Woups, merged this too quickly, I think chore is not the right prefix, or is it ?

**Comment by paddatrapper** [comment]
It is - not user facing. If there is more complicated things required to add support for a particular version of a dependency, then we have to do it and not dependabot. In which case it is a feature/fix depending on the nature of the change

**Comment by jooola** [comment]
Btw, dependabot should be smart enough to guess this, see an example here https://github.com/jooola/earhorn/pull/3

**Comment by paddatrapper** [comment]
That's cool

**Pull request merged**
