### PR TITLE
Add Intro and Outro playlist to Autoloading Playlists

### LINKED ISSUE #693: Include global intro and outro autoloading playlist
**Is your feature request related to a problem? Please describe.**
The basic idea here is that you may want to have a set of station-wide intros such as station IDs that always air at the beginning of a show and you can't rely upon your DJs to always include these. In addition you may want to change your intro playlist for all of your shows say to promo a certain event but don't want to manually edit each of the auto-loading playlists for every show to implement the change. In addition you might want to have a track fill in at the end of every show especially if there wasn't anything scheduled in the track list. An outro playlist would allow for a universal scheduled playlist that could include a time remaining smartblock and so it would always fill in if a show isn't scheduled manually or by the playlist for some reason. 

**Describe the solution you'd like**
Add an intro and outro playlist select from the general setting page. If an autoloading playlist is enabled for a show then the intro would be scheduled before the content of the show. If an outro playlist is selected it would attempt to be added after the content of the shows playlist.

This workflow would allow for a flexible interplay between individual DJ scheduled shows and a stationwide identity and the insertion of sponsorships or underwriting at the beginning or end of shows. 

**Describe alternatives you've considered**
Another alternative would be to enable playlists to contain other playlists so you could have a station wide "intro playlist" that contains different smartblocks of PSAs, events etc. But this would require refactoring the playlist code to allow playlists to be embedded in playlists and this isn't allowed because of potential recursion loops of playlists containing playlists that had the first playlist. 

Another idea was to have a intro playlist and outro playlist for each show that could be selected. This would be more flexible but also more complicated for users to set up and not as straightforward to conceive. Further complicating this idea was to replace the single show autoloading playlist with a playlist of playlists that could be ordered for each show but while this would be powerful it would also be complicated.

Another more complex idea would be to have the intro playlist tracks mixed and play simultaneously with the scheduled content via liquidsoap input mixing, so that an individual shows schedule wouldn't be changed but this would require to much modification to the current setup and could result in some goofy situations.

**Additional context**
The current decision that would need to be made on this would be what options there are to override this intro and outro on individual shows. The simple way of doing this would be to have it only apply to shows that have autoloading playlist enabled on them. That way you could disable it on shows that you didn't want to have something inserted in the beginning. In addition if you wanted to use it just to fill in a station ID and an outro but planned on manually scheduling the content you would enable the autoloading playlist but not select a playlist in the dropdown.

### PR DESCRIPTION
**Pull request by Robbt**
The basic functionality for adding an intro and outro playlist that will be added to autoplaylists.
It needs some debugging as it is giving an error related to the schedule already being updated so I suspect it is a timing thing and they need to be paused so that the previous schedule can complete before the next one happens.

This fixes #693

### CODE REVIEW

**Comment by Robbt** [comment]
So I had to slightly refactor show_instance to basically update the database lastUpdatedTime manually after a playlist is added and now this works fine.

So the code is functional and the only blocker I'd say that exists is we might want to consider a better explanation in the UI and possibly even creating a new page vs. keeping it under general. At the very least tool tips explaining it and a better distinction in the General Page so people can find it would be ideal. @frecuencialibre do you have any ideas or suggestions.

This code was also built on xenial before we switched to the latest z1fs vs. zend. I could update the PR if that is an issue for anyone let me know. I think it is pretty much ready for testing though.

**Comment by frecuencialibre** [comment]
I'm excited to try this! hope to get time monday. I also want to finally
finish the podcast ui one.

**Comment by frecuencialibre** [comment]
hey man, how difficult would it be to get the recent db changes and z1fs in here? i'd like to learn what all this rebase and force pushing business is that i've seen Kyle and Lucas do to keep their PRs up to date with master.

the fact that this branch is 75 commits behind master means that that the only way i've found to test it is with `vagrant up ubuntu-xenial` (now downloading...).  otherwise i can use my docker dev setup to instantly swap between branches that do not require any install steps...

**Comment by Robbt** [comment]
Ok, I tried to pull the z1fs stuff in so that should hopefully make it work without switching to a different VM for testing.

**Comment by frecuencialibre** [comment]
So I can confirm that this PR adds two new playlist select elements in site wide general settings, and those do successfully put their contents at the start/end of shows with autoloading playlists. This appears to happen at the same time that the autoloading playlist is loaded.

I'm also seeing that shows _without_ autoloading playlists are not having intro/outro playlists added to their start/end. is this an intentional design decision?

Gotta run, but hope to post asap more UX thoughts re: this one. Awesome work @Robbt !

**Comment by Robbt** [comment]
Yeah, I'm taking an incremental approach here and so I just made it so I just hooked into the autoloading playlist code. It probably wouldn't be too difficult to add this to every show but I think we need to improve  the UX if we are going to go that way so that people understand what it does. Perhaps there should be a global option that says, apply Intro and Outro playlist to every show.

Another idea that might be something I end up coding is the idea of different intro and outro playlists depending upon the time of day.

**Comment by frecuencialibre** [comment]
I remember discussing how to achieve the goal of quickly "sprinkling" station IDs/jingles/announcements/ads throughout the schedule without breaking LibreTimes "strict scheduling" approach. I'd say that achieving this does necessitate that shows w/o autoloading playlists also be targeted. It could be that autoloading playlists are in very common use by a station (as in our case), but that may not be true for others, and this could be a potential source of confusion.

So i'd like to float a UI proposal here that i think would be very powerful, but which may be beyond scope here. What if we gave folks the ability to decide on a show by show basis whether they'd like to disable or modify the default provided in general settings:

screenshot from 2019-02-12 08-51-18

I also remember scrapping a similar proposal to have multiple autoloading playlists because it was going to over complicate things, but hopefully this proposal is different since we'd putting these in a separate collapse-able section, since we have a distinct and clear use case. whatcha think?

**Comment by Robbt** [comment]
I think this looks good. Having a station wide default and the ability to override on a per show basis. I'd like to play more with what the UX choices will be on the admin side. I also think it might make sense to create a new section outside of general that can be accessed and possibly the program manager role can be given access to this without getting the more technical options revealed.

**Comment by frecuencialibre** [comment]
agreed. it'd be great for program managers to be able to set the station
default intro/outro playlists.

there's also another piece here which we may need to explore, which is
visual communication that these playlists will be included in shows'
scheduled tracks.

**Comment by frecuencialibre** [comment]
This is working great on Ubuntu 16 / PHP 7.0, but i'm getting this error on ubuntu 18 / PHP 7.2 when I attempt to save general settings:

```
2019-02-13T19:57:41+00:00 ERR (3): localhost [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: ErrorException: count(): Parameter must be an array or an object that implements Countable in /vagrant/vendor/zf1s/zend-validate/library/Zend/Validate/File/Count.php:257
Stack trace:
#0 /vagrant/vendor/zf1s/zend-validate/library/Zend/Validate/File/Count.php(257): exception_error_handler(2, 'count(): Parame...', '/vagrant/vendor...', 257, Array)
#1 /vagrant/vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer/Adapter/Abstract.php(649): Zend_Validate_File_Count->isValid('/', Array)
#2 /vagrant/vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer/Adapter/Http.php(148): Zend_File_Transfer_Adapter_Abstract->isValid('stationLogo')
#3 /vagrant/vendor/zf1s/zend-form/library/Zend/Form/Element/File.php(444): Zend_File_Transfer_Adapter_Http->isValid('stationLogo')
#4 /vagrant/vendor/zf1s/zend-form/library/Zend/Form.php(2293): Zend_Form_Element_File->isValid(NULL, Array)
#5 /vagrant/vendor/zf1s/zend-form/library/Zend/Form.php(2308): Zend_Form->isValid(Array)
#6 /vagrant/airtime_mvc/application/controllers/PreferenceController.php(41): Zend_Form->isValid(Array)
#7 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): PreferenceController->indexAction()
#8 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#9 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /vagrant/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /vagrant/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /vagrant/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#13 /vagrant/airtime_mvc/public/index.php(68): require_once('/vagrant/airtim...')
#14 {main}
```

standard vagrant process. another unrelated issue i'll note here out of sheer lazyness is that i also saw this error in the vagrant setup log. looks like we should `apt update`.

```
    ubuntu-bionic: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/libasound2-data_1.1.3-5ubuntu0.1_all.deb  404  Not Found [IP: 91.189.88.162 80]
```

can you reproduce this?

**Comment by Robbt** [comment]
So this issue is unrelated but appears to be another PHP 7.2 and above error that will need to fixed in z1fs. It has to do with the Logo upload using Zend-file transfer.
```#0 /vagrant/vendor/zf1s/zend-validate/library/Zend/Validate/File/Count.php(257): exception_error_handler(2, 'count(): Parame...', '/vagrant/vendor...', 257, Array)
#1 /vagrant/vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer/Adapter/Abstract.php(649): Zend_Validate_File_Count->isValid('/', Array)
#2 /vagrant/vendor/zf1s/zend-file-transfer/library/Zend/File/Transfer/Adapter/Http.php(148): Zend_File_Transfer_Adapter_Abstract->isValid('stationLogo')
#3 /vagrant/vendor/zf1s/zend-form/library/Zend/Form/Element/File.php(444): Zend_File_Transfer_Adapter_Http->isValid('stationLogo')
#4 /vagrant/vendor/zf1s/zend-form/library/Zend/Form.php(2293): Zend_Form_Element_File->isValid(NULL, Array)
#5 /vagrant/vendor/zf1s/zend-form/library/Zend/Form.php(2308): Zend_Form->isValid(Array)
#6 /vagrant/airtime_mvc/application/controllers/PreferenceController.php(41): Zend_Form->isValid(Array)
#7 /vagrant/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): PreferenceController->indexAction()
```
And basically means the general settings page isn't going to work until we push a fix to z1fs.

**Comment by frecuencialibre** [comment]
Merging since 7.2 error above is unrelated to these changes

**Comment by paddatrapper** [comment]
> i'd like to learn what all this rebase and force pushing business is that i've seen Kyle and Lucas do to keep their PRs up to date with master.

@frecuencialibre - I use feature branches and keep master up to date with upstream. Then run `git rebase master` on the feature branch to rebase it off the current master. Any conflicts need to be resolved as they are encountered. Once the rebase is done, I force push the changes to the feature branch - `git push --force`

The docs are here: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Pull request merged**
