### PR TITLE
Update ru and de i18n

### LINKED ISSUE #107: Contributing: Russian translation
Hi! I'd like to contribute for Russian translation of Libretime

### PR DESCRIPTION
**Pull request by hairmare**
Thanks to @korotkov13 and @yarik2720 for translating!

Fixes #107

### CODE REVIEW

**Comment by hairmare** [comment]
Alright, this now contains new translations as well as the code to actually render them in most places. There are still a couple of leftovers and I plan on taking care of those over some time since such translation bugs tend to be tedious to analyze.

**Comment by Robbt** [comment]
Ok, wow the CSS for the web UI is pretty brittle when it comes to different length fields. I tried the de translation and was unable to logout without hacking the CSS. 
This is the change I needed to make so that the logout or  Abmelden wasn't available.
I had to modify the width in masterpanel.css to this so that it would show up.
.personal-block.solo {
	width: 215px;
	line-height: 32px;
	margin: 0;
}

**Comment by hairmare** [comment]
Yay, you figured out the logout link. I had looked at that for quite a while to avail. Your change only seems to fix the issue without breaking the whole topbar like everything I tried.

**Comment by hairmare** [comment]
I keep finding and pushing more i18n bugs. I'm gonna stop on the PR now and keep my stuff for a new PR. I'll have to regenerate and push strings to zanata since there are some that are missing in the code.

**Pull request merged**
