### PR TITLE
Use python namespaces

### LINKED ISSUE #1212: Rename and move apps in the libretime namespace
I propose to rename the new api package to `libretime_api` instead of `libretimeapi`, for consistency with the other tools naming.

`api/libretimeapi/` => `api/libretime_api/`

In some far future, I would even think the python apps could be moved in the root folder.

### PR DESCRIPTION
**Pull request by jooola**
This move all our python packages into the libretime namespace.

Closes #1212 

Depends on #1406 and #1409

:warning: **PLEASE DO NOT SQUASH THIS PR, REBASE IT** :warning:

### CODE REVIEW

**Comment by jooola** [comment]
Django is not really happy with this namespace thing. I found a few bugs in the django code that makes using namespace difficult.

**Comment by jooola** [comment]
Django bug report https://code.djangoproject.com/ticket/33207

@paddatrapper Could you confirm that this bug is not a configuration problem ?

**Comment by paddatrapper** [comment]
The doc update was useful. I have never tried running a namespaced Django project before with a custom user model

**Comment by jooola** [comment]
I was unsure how to read one of the comments, if it was helpful and I didn't understand, or it was a personal opinion just saying don't use namespaces packages.

Anyway, I hoped to merge this faster, I'll probably remove the django namespacing changes and create another PR. I prefer not leaving this open for too long, because it's always a pain to rebase / merge on entire folder renames.

**Comment by jooola** [comment]
Since I don't want to waist my time in making this work with Django, I'll simply leave this branch on hold for now. This can be reconsidered later.

I will propose another PR that do the proper renaming for each libretime packages though.

**Comment by jooola** [comment]
Closing this, if we want to use python namespace we should start fresh from the main branch. Syncing such changes is a waist of time.

**Pull request closed without merging**
