### PR TITLE
Fill Remaining Time Smartblock Limit

### PR DESCRIPTION
**Pull request by Robbt**
So this is my work on building a smartblock that is aware of how much time is remaining in a show instance it is scheduled into and will grow or shrink based upon what is already scheduled. You can see #357 for more discussion on the rationale for the changes and the thought process behind the changes.

TODO still
- [x] -  figure out why it is overflowing the time w/ repeating tracks enabled - see #606 
- [x] - get rid of the sp_limit_value textbox via jquery when "fill remaining time" option is selected

### CODE REVIEW

**Comment by Robbt** [comment]
Ok, so I'm thinking this is ready for test by other people and merging. It is working in all of my tests.

I didn't disable the "time remaining" for static smartblock because to go through and figure out how to make the jquery code work to remove a individual value from the drop down and then add it back with translated text when dynamic smartblock is chosen seems like too much work for little return.

Basically if you generate or preview a time remaining smartblock it will create a 24 hour playlist. This is because this is the maximum time that a show can ever be. If someone selects this for a static smartblock and generates they will just end up with a 24 hour long smartblock. This doesn't seem sufficiently broken to warrant the pain of dealing with jquery. I'm open to feedback from other people if they decide that this isn't the case and we should fix it before merging.

But otherwise I think this code will do a lot to make smartblocks and autoloading playlists more useful for stations wanting to avoid dead air.

**Comment by JohnnyC1951** [comment]
This seems very good indeed. Is it dynamic? IE if an autoloading show arrives via Podcast import, will this will refactor the smartblock length?

**Comment by Robbt** [comment]
Yes, the intention for this is to be used in conjunction with content where you don't necessarily know the length ahead of time. Since podcasts can vary in length if you have a fill remaining time smartblock after say a 56 minute length track in a 60 minute show it will treat it as a 4 minute long smartblock and schedule matches up until that limit. Combined with the fix to repeating tracks and adding an option for tracks you want to allow to overflow with #607 (such as ambient tracks) you can solve the issue that plagues syndicated content where either you have a bunch of content cut off halfway through the track or you have dead air because your filler wasn't long enough.

**Comment by JohnnyC1951** [comment]
At the moment, I have a section of smartblock fillers of like 30 mins, 60 mins, 120 mins and I simply put one of show length after the show podcast smartblock. Nothing bad ever seems to happen, but I guess there is a lot of extra processing going on at show-load time.

**Pull request merged**
