### PR TITLE
feat(legacy): add db config defaults and allow custom port

### PR DESCRIPTION
**Pull request by jooola**
Add a port field (`database.port`) to the database config section.

BREAKING CHANGE: the database section in the config file has been updated:
- `database.dbname` was renamed to `database.name`
- `database.dbuser` was renamed to `database.user`
- `database.dbpass` was renamed to `database.password`

### CODE REVIEW

**Comment by jooola** [comment]
Please squash

**Comment by jooola** [comment]
You mean the general documentation ? Or the airtime > libretime migration documentation ?

**Comment by paddatrapper** [comment]
Both. The airtime to libretime migration path will need a step updating the config file

**Comment by jooola** [comment]
I added some documentation, but maybe it isn't enough.

**Comment by paddatrapper** [comment]
I'm happy with that, pointing to the example ensures that there is consistency if anything else changes and we keep things DRY

**Comment by jooola** [comment]
Rebased to fix conflicts

**Comment by jooola** [comment]
The breaking change information in the PR description has not been included in the squashed commit.

It should be included in #1620

**Comment by narcisgarcia** [comment]
Is this related to issue #1020  ?

**Comment by jooola** [comment]
> Is this related to issue https://github.com/libretime/libretime/issues/1020 ?

No, this if for the database connection configuration.

**Pull request merged**
