### PR TITLE
3.0.x

### PR DESCRIPTION
**Pull request by amin1562**
### Description

# docker-compose run --rm api libretime-api migrate
/snap/docker/2343/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Pulling rabbitmq (rabbitmq:alpine)...
alpine: Pulling from library/rabbitmq
8921db27df28: Pull complete
a13940706f51: Pull complete
e6020063b14e: Pull complete
3cd0f1839ab4: Pull complete
3037b514b070: Pull complete
307cbc98ab1e: Pull complete
7cb5dee1fd14: Pull complete
3e05d2e4ae54: Pull complete
92eafbc9c323: Pull complete
5bb6593057bb: Pull complete
Digest: sha256:c6fb51b63a5d6f13d95aab8c0baf88ec44de00b0ae0f21bab6d4b61d734e40aa
Status: Downloaded newer image for rabbitmq:alpine
Pulling api (ghcr.io/libretime/libretime-api:latest)...
latest: Pulling from libretime/libretime-api
025c56f98b67: Pull complete
778656c04542: Pull complete
871f7ecfc73e: Pull complete
0e69c18ce14d: Pull complete
d5aa0f99f766: Pull complete
eea4e7f06d5a: Pull complete
1b4ee50f9736: Pull complete
71e6ed49d9cc: Pull complete
482c60ef1867: Pull complete
573b494a8cc8: Pull complete
98c2e1e42792: Pull complete
0f92c9274282: Pull complete
1575b839ff4d: Pull complete
caf424050ced: Pull complete
3fb1f1bc3a7f: Pull complete
4262424525e6: Pull complete
3b3c8e5ce38e: Pull complete
397b76389d4b: Pull complete
47b88828f215: Pull complete
Digest: sha256:065081b40e1c269a73f4537aa4b36cd240fc9ced6b5459deaa90f4b3ca81a6e8
Status: Downloaded newer image for ghcr.io/libretime/libretime-api:latest
Creating root_postgres_1 ... done
Creating root_rabbitmq_1 ... done
Creating root_api_run    ... done
        2023-01-16 20:52:50.563 | CRITICAL | libretime_shared.config._base:__init__:50 - 2 validation errors for Config
general -> public_url
  none is not an allowed value (type=type_error.none.not_allowed)
general -> api_key
  none is not an allowed value (type=type_error.none.not_allowed)
ERROR: 1

what should i do???

**This is a new feature**:

_Do the changes in this PR implement a new feature?_

**I have updated the documentation to reflect these changes**:

_Are there documentation changes required as a result of these changes? See
https://github.com/libretime/libretime/wiki/Documentation-Requirements_

### Testing Notes

**What I did:**

_What did you do to validate this PR?_

**How you can replicate my testing:**

_How can the reviewer validate this PR?_

### **Links**

_Issues links or other related resources. Use the line Closes: #bug_number to
link a bug in the issue tracker._

### CODE REVIEW

**Comment by amin1562** [comment]
update, that one fixed here is the new error

 docker-compose up -d
/snap/docker/2343/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
root_rabbitmq_1 is up-to-date
root_postgres_1 is up-to-date
Starting root_worker_1 ...
Recreating root_icecast_1 ...
Starting root_worker_1     ... done
Recreating root_icecast_1  ... done
Starting root_analyzer_1   ... done
Starting root_playout_1    ... done
Starting root_liquidsoap_1 ... done
Starting root_nginx_1      ... error

ERROR: for root_nginx_1  Cannot start service nginx: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/nginx.conf" to rootfs at "/etc/nginx/conf.d/default.conf": mount /root/nginx.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/nginx.conf" to rootfs at "/etc/nginx/conf.d/default.conf": mount /root/nginx.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by amin1562** [comment]
I fixed problem,but the web panel isn't open in port 80, there is nothing opened for web panel

docker-compose run --rm api libretime-api migrate
/snap/docker/2343/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Creating root_api_run ... done
Operations to perform:
  Apply all migrations: auth, contenttypes, legacy, sessions
Running migrations:
  No migrations to apply.
  
  docker-compose up -d
/snap/docker/2343/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Creating network "root_default" with the default driver
Creating root_icecast_1  ... done
Creating root_rabbitmq_1 ... done
Creating root_postgres_1   ... done
Creating root_analyzer_1   ... done
Creating root_liquidsoap_1 ... done
Creating root_worker_1     ... done
Creating root_playout_1    ... done
Creating root_api_1        ... done
Creating root_legacy_1     ... done
Creating root_nginx_1      ... done

---------------
and these are the ports that using

docker-pr 247210            root    4u  IPv4 3316405      0t0  TCP *:8000 (LISTEN)
docker-pr 247217            root    4u  IPv6 3315370      0t0  TCP *:8000 (LISTEN)
docker-pr 247583            root    4u  IPv4 3319825      0t0  TCP *:8002 (LISTEN)
docker-pr 247590            root    4u  IPv6 3319828      0t0  TCP *:8002 (LISTEN)
docker-pr 247610            root    4u  IPv4 3319881      0t0  TCP *:8001 (LISTEN)
docker-pr 247616            root    4u  IPv6 3319886      0t0  TCP *:8001 (LISTEN)
docker-pr 248186            root    4u  IPv4 3322892      0t0  TCP *:8080 (LISTEN)
docker-pr 248193            root    4u  IPv6 3322897      0t0  TCP *:8080 (LISTEN)

**Comment by amin1562** [comment]
I even tried with the installer

  libretime-analyzer.service                                                                       loaded    active   running   LibreTime Media Analyzer Service
  libretime-api.service                                                                            loaded    active   running   LibreTime API Service
  libretime-liquidsoap.service                                                                     loaded    active   running   LibreTime Liquidsoap Service
  libretime-playout.service                                                                        loaded    active   running   LibreTime Playout Service
  libretime-worker.service                                                                         loaded    active   running   LibreTime Worker Service
  libretime-api.socket                                                                             loaded    active   running   LibreTime API Socket
  libretime.target                                                                                 loaded    active   active    LibreTime Services
  
  but still no web panel
  ---------
  is that because of pulic url?
  
general:
  # The public url.
  # > this field is REQUIRED
  public_url: https://0.0.0.0/
  # The internal API authentication key.
  # > this field is REQUIRED
  api_key: dit4fW3YP8RJJ5ebwtSH9s7y9GJVspJq

**Comment by paddatrapper** [comment]
It uses port 8080 for web and public_url should too if it is not behind a proxy. Please go through the docker setup in the documentation at https://libretime.org.

Also in future please use discourse for installation questions or the issue tracker for bug reports. Opening a Pull Request is not the correct way to ask for help

**Pull request closed without merging**
