### PR TITLE
chore: release 3.1.0

### PR DESCRIPTION
**Pull request by jooola**
I'd like to start thinking about releasing 3.1.0.

There are some issues still open on the 3.1.0 milestone, I've moved some of them to the 3.2.0 milestone. Is there anythingelse that must go into 3.1.0 ?

### CODE REVIEW

**Comment by paddatrapper** [comment]
This is blocked by #2498 I guess?

**Comment by jooola** [comment]
I was hoping to close the entire milestone, but maybe that's too much and we need to release sooner ?

**Comment by paddatrapper** [comment]
I think we can hold off to complete the milestone

**Comment by jooola** [comment]
Once #2567 is merged, I'll be able to prepare the 3.1.0 release, test it and maybe even publish it today!

**Comment by jooola** [comment]
So, I've tested a deployment using vagrant, as well as an upgrade from stable to the current main. Everything seem to be working fine.

I've been running from the main branch in production for the different PR's that needed testing. So I think the overall state of main is stable.

I think we could release today, if there is no other blockers, @paddatrapper what do you think ?

**Pull request merged**
