### PR TITLE
Add postgres and rabbitmq password update scripts

### PR DESCRIPTION
**Pull request by jooola**
I use this often to make clean install on my staging environment, though it could be committed back to the main repo.

This is only for advanced user who might stumble on this file.

### CODE REVIEW

**Comment by paddatrapper** [comment]
This changes the Postgres and RabbitMQ passwords, so the name should probably reflect that.the installer also sets the icecast password

**Comment by jooola** [comment]
@paddatrapper Just exploded the script in 2 separate script.

**Comment by jooola** [comment]
Woups, some typo in the middle

**Comment by jooola** [comment]
Ok good to go !

**Comment by paddatrapper** [comment]
Do we want to reference them from the How to change default passwords documentation? https://libretime.org/docs/default-passwords

**Comment by jooola** [comment]
I'd rather not, this should more be something for a proper `libretime-ctl` cli utility. But feel free to add it.

**Pull request merged**
