### PR TITLE
chore: clean schedule messages

### PR DESCRIPTION
**Pull request by jooola**

### CODE REVIEW

**Comment by paddatrapper** [comment]
Are those the only values used?

**Comment by jooola** [comment]
> Are those the only values used?

From the code I read yeah, I'll do some testing.

**Comment by paddatrapper** [comment]
Makes sense - the artist and title are the only file metadata items that can be displayed as stream metadata

**Comment by jooola** [comment]
Ok, just schedules some files, metadata show up in icecast. This is ready.

**Pull request merged**
