### PR TITLE
Modified install script to install PyOpenSSL for Ubuntu 14.04 for air…

### LINKED ISSUE #57: Problem: Podcasts failing to download from libsyn due to SSL error
I was trying to download DemocracyNow's podcast and a number of errors cropped up in the log regarding SSL.

From the looks of the log here, there might be something we need to do.

[2017-03-10 15:22:39,352: WARNING/PoolWorker-2] /usr/local/lib/python2.7/dist-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
[2017-03-10 15:22:40,042: ERROR/PoolWorker-2] Certificate did not match expected hostname: traffic.libsyn.com. Certificate: {'notAfter': 'Jan 23 21:04:38 2018 GMT', 'subjectAltName': (('DNS', '*.app.libsynpro.com'), ('DNS', 'app.libsynpro.com')), 'subject': ((('organizationalUnitName', u'Domain Control Validated'),), (('commonName', u'*.app.libsynpro.com'),))}
[2017-03-10 15:22:40,045: INFO/PoolWorker-2] podcast-download[php_58c30b0e82b7c9.35832819]: Error during file download: hostname 'traffic.libsyn.com' doesn't match either of '*.app.libsynpro.com', 'app.libsynpro.com'
[2017-03-10 15:22:40,052: ERROR/PoolWorker-2] Task podcast-download[php_58c30b0e82b7c9.35832819] raised unexpected: TypeError('SSLError(CertificateError("hostname \'traffic.libsyn.com\' doesn\'t match either of \'*.app.libsynpro.com\', \'app.libsynpro.com\'",),) is not JSON serializable',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery-4.0.2-py2.7.egg/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery-4.0.2-py2.7.egg/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/airtime_celery-0.1-py2.7.egg/airtime-celery/tasks.py", line 173, in podcast_download
    return json.dumps(obj)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: SSLError(CertificateError("hostname 'traffic.libsyn.com' doesn't match either of '*.app.libsynpro.com', 'app.libsynpro.com'",),) is not JSON serializable

### PR DESCRIPTION
**Pull request by Robbt**
…time-celery SSL fix
This fixes #57 for Ubuntu 14.04 at least. Will need to revisit. I also still need to test it from a empty installation.

### CODE REVIEW

**Comment by Robbt** [comment]
I need to modify the Ubuntu 14.04 pip install command to use the --upgrade so that it installs the latest version of pyopenssl. I tested this on a blank install and it worked.

**Comment by hairmare** [comment]
I got sidetracked trying to reproduce this on CentOS and found that the podcast downloader is not unicode safe at all. My fix for the unicode issue is in #60.

I'll give this a test as soon as I have switched back to Ubuntu and merge it then.

**Comment by hairmare** [comment]
I'm seeing this on other distros as well. I'll try it on some clean installs but it might take a while.

**Comment by hairmare** [comment]
Turns out, debian/jessie is the only distro in `installer/lib` that has a python2 that does SNI out of the box. I'm merging this since it works. I also have a refactor for it ready on my local centos branch. The branch also fully adds debian support. I'm preparing those change so I can push them now.

In a couple of iterations I should have the boxes be able to run in parallel to each other :) I'll also do some more manual testing as soon as I'm back to a ubuntu box after a couple of vagrant up runs.

**Comment by hairmare** [comment]
My changes for other distros are in #64.

**Pull request merged**
