### PR TITLE
chore: release 3.0.0-alpha.13

### LINKED ISSUE #1891: Playout fails because of missing api schedule fields filtering
This has been fixes in eef789e4d1add2470c237df7ecce3dd574aedcad and 9babb0c4f093b6a3a7cfb4383b9a966d993c8832 but I expect freshly installed or upgraded instances to face this problem.

This started on 2022-06-17.

A hotfix is to pin the django-filter package to `21.1` as the recent release introduced problematic changes. See https://github.com/carltongibson/django-filter/blob/main/CHANGES.rst#version-221-2022-6-17
 
I think we should cut a release soon.

### PR DESCRIPTION
**Pull request by jooola**
Here is what I expect to have merged before we release this version:
- #1877
- #1892
- #1868
- #1637
- #1719
- #1186
- #1953

Feel free to raise any other issue or PR that should be present in this release.

Fixes #1891

### CODE REVIEW

**Comment by jooola** [comment]
Weird, the vagrant focal setup doesn't work with apt-cacher-ng I get some weird:
```
    focal: W
    focal: : 
    focal: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/focal/InRelease  500  Remote or cache error [IP: 192.168.121.1 3142]
    focal: W
    focal: : 
    focal: Some index files failed to download. They have been ignored, or old ones used instead.

```

Does this happen to you too ?

**Comment by paddatrapper** [comment]
It works for me

**Comment by jooola** [comment]
> Navigating to the site after running `vagrant up focal` throws an error on `main` at the moment:
> 
> ```
> 2022/07/12 19:27:51 [error] 53055#53055: *228 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'League\Uri\Uri' not found in /vagrant/legacy/application/configs/conf.php:154
> Stack trace:
> #0 /vagrant/legacy/application/configs/conf.php(28): Config::validateUrl()
> #1 /vagrant/legacy/application/configs/conf.php(122): Config::loadConfig()
> #2 /vagrant/legacy/application/Bootstrap.php(5): Config::getConfig()
> #3 /vagrant/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(340): require_once('/vagrant/legacy...')
> #4 /vagrant/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(202): Zend_Application->setBootstrap()
> #5 /vagrant/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(99): Zend_Application->setOptions()
> #6 /vagrant/legacy/application/airtime-boot.php(62): Zend_Application->__construct()
> #7 /vagrant/legacy/public/index.php(56): require_once('/vagrant/legacy...')
> #8 {main}
>   thrown in /vagrant/legacy/application/configs/conf.php on line 154" while reading response header from upstream, client: 192.168.10.100, server: , request: "GET /api/get-stream-setting/format/json/api_key/Xw1MBQeVn1VMLYZjwXvNk5J9vSV2VOh6/ HTTP/1.1", upstream: "fastcgi://unix:/run/libretime-legacy.sock:", host: "192.168.10.100:8080"
> ```

I think you have some install/caching error, you might need to clean the repo before installing. I just installed on focal and I don't have this error.

**Comment by paddatrapper** [comment]
Same error after a `git clean -xf`

**Comment by jooola** [comment]
> Same error after a `git clean -xf`

You need to recurse into the legacy folder. You can use the `make clean` command or `git clean -xdf */`.

I usually prefer not to clean using `git clean -xdf` because it removes the `.vagrant` dir.

**Comment by paddatrapper** [comment]
It did recurse - removed the PHP CS cleaner cache in legacy

**Comment by paddatrapper** [comment]
Things look good to me

**Comment by jooola** [comment]
Cool, I've upgrade my production to the main branch, no issues so far.

I think I'll cut this release this afternoon.

**Comment by paddatrapper** [comment]
Thanks!

**Comment by jooola** [comment]
My pleasure! Hope I didn't miss anything.

**Pull request merged**
