### PR TITLE
Improve CONTRIBUTING and community links

### PR DESCRIPTION
**Pull request by jooola**
- Enhance CONTRIBUTING.md file.
- Add extra links to issue chooser.

Merge after #1210 is in master.

### CODE REVIEW

**Comment by paddatrapper** [comment]
This should also probably update `docs/_docs/contributing.md`

**Comment by jooola** [comment]
Aah ok ! What about trying to have a single source of truth for these files ? One could a dump link to the GitHub contributing.md file from the website ?

Yes, feel free to push on this branch.

**Comment by paddatrapper** [comment]
Having a single source of truth would be good. Not sure if it should be CONTRIBUTING or the docs though

**Comment by jooola** [comment]
Maybe merge both documents and symlink one to the other ? Would you and @gusaus like to do this ?

**Comment by paddatrapper** [comment]
I've pushed 095a172303f51e1f92c1cb4b9a5ba372de5ffd18 and 6cbe769471298e12b0c81a2d2d66dc1d3ae71792 to my branch with some reworking of this to include financial stuff and indicate the division I see between the docs and CONTRIBUTING.md. I see CONTRIBUTING.md to be more useful for bug submission (as GitHub links to it) and have handed off everything else to the website documentation. @jooola let me know what you think. @gusaus your input around the financial contribution stuff would be nice too

**Comment by jooola** [comment]
I don't think putting most of the contribution guidelines on the website is a good idea. Splitting it in 2 is a good idea though.

Maybe we need to define what this documents are intended to. From my perspective it is a mix of where to start for contributing and what are the guidelines for contributing. And this might need to change by moving the guidelines in some other files.

For instance the bug/enhancements guidelines should be written in the .github/ISSUE_TEMPLATES/* files, but `what are the steps to open a ticket` should be in the CONTRIBUTING.md file.
Applied to the documentation, guidelines should go in the docs folder, but how to go there is in CONTRIBUTING.md or the website.

All this is with the idea of preventing duplicates and try to have a must single source of truth.

On the website /contribute:
- Code of conduct
- The financial guidelines
- Possible translations guidelines.
- Documentation guidelines
- Community channels
 
In the repo CONTRIBUTING.md:
- documentation guidelines with dedicated section for a link to the website section.
- Issues 
- Enhancements
- Write Code (definitely in the repo)
- Testing (definitely in the repo)
- CI/CD (definitely in the repo)
- Modifying the Database (definitely in the repo)

I think this is better, as for someone who want to write code or fix the CI will jump the the Github repo directly.

Maybe this is out of scope for this PR, but we need to consider either moving dev documentation in the github wiki, or move the github wiki in the website.

**Comment by paddatrapper** [comment]
Sounds good. Most of those sections are there somewhere at the moment. Do you want to place them correctly or shall I?

**Comment by paddatrapper** [comment]
I've reordered them in fec0aec26. I left the bugs and enhancement guides in both, as those are things people just entering the project need

**Comment by paddatrapper** [comment]
If you're happy, feel free to pull those (095a172303f51e1f92c1cb4b9a5ba372de5ffd18, 6cbe769471298e12b0c81a2d2d66dc1d3ae71792, fec0aec26d6fb172f2908fdcc838212f35f00b8b) into your branch and I can merge

**Pull request merged**
