### PR TITLE
Ensure that the python version under test is installed

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes the current travis failures for Python 3.7

### CODE REVIEW

**Comment by paddatrapper** [comment]
I don't understand why this is still requiring cairo 1.15.10... That requirement was only introduced in PyCairo 1.20.0, which I am explicitly not installing

**Comment by zklosko** [comment]
Are you looking for this one? https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libcairo2_1.15.10-2_amd64.deb.html

**Comment by paddatrapper** [comment]
Thanks, that is very helpful!

**Comment by paddatrapper** [comment]
Not fixed by that PR

**Pull request closed without merging**
