### PR TITLE
Rename all systemd, sysvinit and upstart files to libretime

### PR DESCRIPTION
**Pull request by paddatrapper**
Also cleans up all documentation and website references to sysvinit calls to use systemd

Fixes: #516

### CODE REVIEW

**Comment by Robbt** [comment]
Ok, this seems to work. Noticed one spot where you forgot to change airtime-liquidsoap to libretime-liquidsoap as well - in build/airtime-setup/forms/finish-settings.php

It seems like a good time to also strip out some of the references to welcome to airtime etc.

Not sure if we should go as far as renaming /etc/airtime to /etc/libretime/libretime.conf and the like or if that would potentially cause headaches to upgraders but it might be a good idea to do all of this stuff at once now that we are switching to python3.

Thanks for starting this process.

**Comment by paddatrapper** [comment]
I think moving the config file would be a good idea for 3.0, but needs a migration plan. Symlink to airtime.conf for upgrades perhaps? I also think that the systemd symlinks made here should only happen on upgrade.

**Comment by Robbt** [comment]
Yeah, we really should work on having a functional upgrade or at least making it not rely upon a misconfiguration that treats every upgrade as a new install as noted in #940

**Comment by Robbt** [comment]
So I suggest we fix https://github.com/paddatrapper/libretime/blob/a254a3222ecd668241eeae453d78814709505ebf/airtime_mvc/build/airtime-setup/forms/finish-settings.php#L8-L16 and change the airtime-liquidsoap to libretime-liquidsoap and then we could merge this (unless we want to do further changes regarding the aliases only being used on upgrades).

**Comment by paddatrapper** [comment]
I've fixed the references, and made the symlink only occur when the old systemd unit exists and is not already a symlink.This should ensure that the migration only occurs once on systems that have existing installs and not at all on new installs.

**Comment by Robbt** [comment]
I tried testing it up on a upgrade of my Debian Buster virtual machine and I don't think the aliases are working after running the install script. So that code might need some work.

**Comment by paddatrapper** [comment]
Vagrant upgrades seem to be weird... They scrap the airtime.conf file too.

What is the output of `ls /etc/system/systemd/`?

**Comment by Robbt** [comment]
Actually I think it is our upgrade process that scraps the /etc/airtime/airtime.conf as referenced above, it always thinks that it is a new install, but maybe it is specific to vagrant.

**Comment by paddatrapper** [comment]
Interesting. To be fair, I have never run subsequent install steps in production. I tend to just destroy the LXC container and create a new one for upgrades

**Comment by paddatrapper** [comment]
@Robbt fixed the issue. It was due to on upgrade, the installer happily removing all systemd units that were installed previously

**Pull request merged**
