### PR TITLE
(site) add site from ned-kelly/libretime-website

### PR DESCRIPTION
**Pull request by frecuencialibre**
straight from https://github.com/ned-kelly/libretime-website

### CODE REVIEW

**Comment by Robbt** [comment]
I'm onboard with @ned-kelly becoming a maintainer. I am excited that we are growing the project. I'm not sure how to do all of the stuff behind the scenes as far as github goes, but it might make sense to have a maintainers coordination discussion. We could do it on here, via RT chat (might be tricky considering the timezone differences) or on the forum.

I think the trickiest thing at this point is figuring out who is going to do what. For instance in this particular PR should we redo it to include the commits in @hairmare added and if so what exactly are the steps to do this.

**Comment by frecuencialibre** [comment]
> I'm onboard with @ned-kelly becoming a maintainer.

consensus! could you go ahead and do this @Robbt ?

> it might make sense to have a maintainers coordination discussion.

definitely. very necessary. weekdays in the mornings (CST, or UTC/GMT -6 hours) are generally best but i can be flexible. perhaps in slack? are audio conference calls possible in slack?

>  should we redo it to include the commits in @hairmare added 

i personally don't think the site commit history is necessary. Ned's docker repo is however a different story -- with both a meaningful commit history and [issues](https://github.com/ned-kelly/docker-multicontainer-libretime/issues) that would be good to keep.

take care everybody!

**Comment by Robbt** [comment]
Great, I sent the invite to @ned-kelly 

I personally think that the commits might be useful to show what changes were made from the default template but it probably isn't too important.

As far as transferring issues it appears that just last month this was added to Github beta so I think we can probably use it - see this [discussion](https://stackoverflow.com/questions/9720718/how-do-i-move-an-issue-on-github-to-another-repo) and here's the [doc](https://help.github.com/articles/transferring-an-issue-to-another-repository/)

**Comment by Robbt** [comment]
I just create a PR with @hairmare work that retained the @ned-kelly commits at #590 - since that was easy to do. I'm not sure if it is ready to merge as it includes some work on the travis CI config. If we decide to merge that we can just close this one.

**Comment by frecuencialibre** [comment]
> I just create a PR

awesome! closing this one. 

> As far as transferring issues 

my understanding of @ned-kelly 's suggestion is to simply transfer the entire repo. however he'd [need repository creation permissions](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/). would that be a problem? i think maintainers team members currently do not have that permission:
screenshot from 2018-11-09 10-43-25

thanks!
-r

**Comment by frecuencialibre** [comment]
baddass. thanks for the research @Robbt . i'd say that if @hairmare can't
answer this weekend then it'd be good to do whatever you see fit to get us
past this bottleneck. for my part, i'm chill with whatever. sorry to be of
zero help with the github stuff.

**Pull request closed without merging**
