### PR TITLE
Auto playlist ui

### PR DESCRIPTION
**Pull request by frecuencialibre**
as of https://github.com/LibreTime/libretime/commit/b60d4581ee15da6f13a01ce981055f28cd4881e5 this is a bare-minimum solution to the problem described in #560. It does this:

screenshot from 2018-11-20 16-19-08

IMO this could be merged as-is, but would be much better if we removed the checkbox. Selecting "None" with the select field would be equivalent to an unchecked checkbox. I'd love to achieve this final result:

screenshot from 2018-11-20 16-25-37
 
I started attempting removing the checkbox, but ran up against an issue: selecting "None" seems to be "forgotten" by the UI. Said another way, if you 1. select a playlist, 2. save the show, 3. edit the show again and select "None", 4. save the show, 5. edit the show _again_, you'll see the show selected in step 1 still active. This behavior is present in the master branch prior to any changes in this PR. I stopped because I ran out of time and started touching so many files that I decided not to risk causing unintended side effects. All help or feedback appreciated!

### CODE REVIEW

**Comment by Robbt** [comment]
I tried to test this and it ran into conflicts with master (I suspect this is because of where we merged in your previous change to make everything collapsed and this was based upon master before that was merged). I'm not sure but I'll let you take a first stab on resolving it but I can help if you are equally uncertain as to what happened.

As far as extending Zend_Form_Element_Select this seems like it could require a bit more digging into Zend1 that I think might be warranted to fix this I found this [discussion](https://stackoverflow.com/questions/45332405/extend-functionality-of-zend-form-element) on stackoverflow about extending it. 

I guess its just frustrating to still be stuck on Zend 1 and still have no clear path forward at this point aside from rewriting everything. I must say we are tremendously lucky that you @hairmare had this job experience working in Zend 1, it has been invaluable with just figuring out how to get LibreTime operational.

**Comment by frecuencialibre** [comment]
thanks all for taking time to look into Zend etc. I think the merge conflict is now fixed.

Based on your feedback I doubt I'll have the bandwidth to dig into Zend, so if that's going to happen it would need to be a contribution from someone else. However, one quick change i could make would be to swap out the tooltip you can see in the first screenshot for the text you can see in the second. any preference either way?

> clear path forward

at this point, and especially after this first adventure into Zend 1 land, i'm thinking that my long-term (ie. post LT 3.0.0) plan to help design and create a mobile-first radio admin tool with great UX will probably be best built with [azuracast](https://github.com/AzuraCast/AzuraCast/). obviously there'd be lots of work to do there too. many features present in libretime are missing in azuracast (metadata management, smartblocks within playlists, graphic creation of playlists, user management integrated with the schedule, etc. etc.), but the project has much less technical debt, appears to be more stable, has mature docker support and upgrade paths, and even work started on an API to enable decoupling. who knows, i mention it here though in the spirit of joining forces and thinking flexibly about all options.

**Comment by Robbt** [comment]
Well I was curious about this because I'm a sucker for pain and I did find people discussing [this exact problem](https://github.com/zendframework/zendframework/issues/2761) but upon further analysis it appears that they are talking about Zend 2.

My suggestion would be to combine the two, keep the hover smart tip but then also add the text underneath the checkmark and above the select option. That way it becomes very clear for them.
Also I noticed one small typo in the word information in the tool tip.

Also while it would probably make sense in an ideal UI world to have the autoplaylist turn on or off based upon whether they selected a playlist vs. requiring an additional checkbox, the additional checkbox ties directly into the database and the extra work to make the database flag set to 0 when none is selected and then 1 when a playlist is selected is probably not worth the effort. I have found when working with Zend to look for the easiest way of accomplishing the goal.

With regards to Azuracast, that might be a good path forward. My vision for LibreTime is to start building a well documented API and decoupling the Zend components and replacing the UI with a modern javascript framework. This is all easier said than done but until we get off of Zend we will continue to run into issues like this. But yeah many hands make light work and this project for better or worse has been a real community effort all along. And if it is going to work we need to make it easier for people to contribute and have it depend upon software that isn't unsupported.

**Comment by frecuencialibre** [comment]
hopefully this is now ready for merge. and should close #560 

screenshot from 2018-11-25 14-46-15
screenshot from 2018-11-25 14-46-20

**Comment by hairmare** [comment]
For some reason the diff looks like this will revert some recent changes.

**Comment by hairmare** [comment]
To make stuff translatable it's usually enough to wrap the strings in `_()`. Rebuilding the translation files doesn't need to be in the same PR as any missing strings will default to what's passed to `_()`. I've been meaning to finally get back onto #78 to clean up things related to i18n.

**Comment by frecuencialibre** [comment]
please disregard this PR. replaced by https://github.com/LibreTime/libretime/pull/611

**Pull request closed without merging**
