### PR TITLE
Allow fixed stream label to be used in all sources

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes: #162

Needs testing, my vagrant setup isn't playing nicely today

### CODE REVIEW

**Comment by paddatrapper** [comment]
Does someone have a moment to review this?

**Comment by zklosko** [comment]
My vagrant setup still doesn't want to work, but I can load this up in Multipass and take a look.

**Comment by zklosko** [comment]
Ubuntu Bionic isn't a fan for the install process. You may need to fast-forward or rebase your branch in order to bring the unchanged code up to the most recent version of Libretime.

```
Unable to correct missing packages.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gstreamer1.0/libgstreamer1.0-0_1.14.5-0ubuntu1~18.04.1_amd64.deb  Undetermined Error [IP: 91.189.88.142 80]
E: Aborting install.
install: line 731: php: command not found
```

**Comment by zklosko** [comment]
Can not connect to the streaming server
    Problem with Liquidsoap...

**Comment by paddatrapper** [comment]
Do you have any logs I can work with?

**Comment by zklosko** [comment]
From `/var/logs/airtime/pypo`:

```
2020-11-23 14:01:25,118 [__main__] [INFO ]  Timezone: ('EST', 'EDT')
2020-11-23 14:01:25,120 [__main__] [INFO ]  UTC time: 2020-11-23 19:01:25.120685
2020-11-23 14:01:25,593 [api_client] [INFO ]  Airtime API version found: 1.1
2020-11-23 14:01:25,593 [api_client] [INFO ]  pypo is only compatible with API version: 1.1
2020-11-23 14:01:26,083 [__main__] [ERROR]  [Errno 111] Connection refused
2020-11-23 14:01:26,089 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
```

Etc.

I did manually restart a few services who claimed to not be running but this did not fix the error. Config is standard.

```
[pypo]
api_client = 'airtime'
cache_dir = '/var/tmp/airtime/pypo/cache/'
file_dir = '/var/tmp/airtime/pypo/files/' 
tmp_dir = '/var/tmp/airtime/pypo/tmp/'
cache_base_dir = '/var/tmp/airtime/pypo'
log_base_dir = '/var/log/airtime'
pypo_log_dir = '/var/log/airtime/pypo'
liquidsoap_log_dir = '/var/log/airtime/pypo-liquidsoap'
ls_host = '127.0.0.1'
ls_port = '1234'
poll_interval = 3600
push_interval = 1
cue_style = 'pre'
record_bitrate = 256
record_samplerate = 44100
record_channels = 2
record_sample_size = 16
record_file_type = 'ogg'
base_recorded_files = '/var/tmp/airtime/show-recorder/'
```

**Comment by paddatrapper** [comment]
I can't replicate the issue with a clean vagrant instance. Can you describe the steps that you followed to get to the error?

**Comment by zklosko** [comment]
I wasn't using Vagrant. I still have yet to get it to work.

Manually create a new VM, git clone libretime, sudo bash install -fiap.

**Comment by paddatrapper** [comment]
And then? Do you do anything before viewing the logs? Do you run through the config setup?

**Comment by zklosko** [comment]
I did run through the config setup and was even able to upload and schedule tracks.

**Comment by paddatrapper** [comment]
Can you please give me a step-by-step account up to the error?

e.g.

1. Create VM
2. `git clone https://github.com/paddatrapper/libretime`
2. `git checkout liquidsoap-title`
3. `sudo ./install -fap`
4. Complete setup without changing defaults
5. `cat /var/log/airtime/pypy/pypo.log`

**Comment by zklosko** [comment]
I did it exactly the way you mentioned, except using -fiap to install Icecast as well. Logs follow:

```
2020-11-29 20:06:36,522 [__main__] [INFO ]  ###########################################
2020-11-29 20:06:36,537 [__main__] [INFO ]  #             *** pypo  ***               #
2020-11-29 20:06:36,538 [__main__] [INFO ]  #   Liquidsoap Scheduled Playout System   #
2020-11-29 20:06:36,538 [__main__] [INFO ]  ###########################################
2020-11-29 20:06:36,539 [__main__] [INFO ]  Timezone: ('EST', 'EDT')
2020-11-29 20:06:36,539 [__main__] [INFO ]  UTC time: 2020-11-30 01:06:36.539428
2020-11-29 20:06:39,025 [api_client] [INFO ]  Unable to get Airtime API version number.

2020-11-29 20:06:44,207 [api_client] [INFO ]  Airtime API version found: 1.1
2020-11-29 20:06:44,207 [api_client] [INFO ]  pypo is only compatible with API version: 1.1
2020-11-29 20:06:44,526 [__main__] [ERROR]  [Errno 111] Connection refused
2020-11-29 20:06:44,530 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
2020-11-29 20:06:45,549 [__main__] [ERROR]  [Errno 111] Connection refused
2020-11-29 20:06:45,550 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
2020-11-29 20:06:46,552 [__main__] [ERROR]  [Errno 111] Connection refused
2020-11-29 20:06:46,552 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
```

Maybe it has to do with Pypo's inability to find the API version number?

**Comment by paddatrapper** [comment]
> ```
> 2020-11-29 20:06:44,207 [api_client] [INFO ]  Airtime API version found: 1.1
> 2020-11-29 20:06:44,207 [api_client] [INFO ]  pypo is only compatible with API version: 1.1
> ```

Seems to be matching correctly

**Comment by zklosko** [comment]
I'm just as stumped

**Comment by hairmare** [comment]
There is two of them :( 

https://github.com/LibreTime/libretime/blob/b73adda6377e21ec5d3ba5cbf81427ae5f0348d1/python_apps/api_clients/api_clients/api_client.py#L224-L233

Smells like a unicode issue or (rather unrealistic) something related to having alphas and betas. Maybe introduced with py3 being more unicode. It might also be liquidsoap version related but I'm assuming you're on /deb packages so that is probably not the issue.

Is this a beta-3 blocker btw?

side note: whe should get rid of the `[0:3]` implementation that I'm sure has it's limits and replace it with semver.

**Comment by paddatrapper** [comment]
There is a semver comp method in there somewhere that I can probably use here. And will definitely update those logging messages..

**Comment by paddatrapper** [comment]
> Is this a beta-3 blocker btw?

No. This is just a nice to have. 

I have updated the logging messages, so hopefully we can get a better idea if that is where this is failing for @zklosko. The semver matching I won't include in this PR, but will update as part of #958 as that re-works much of the api_client

**Comment by zklosko** [comment]
@paddatrapper I was just able to get this to install successfully

**Comment by zklosko** [comment]
The Pypo and Libretime Analyzer keep crashing.

```
time-liquidsoap.service: Main process exited, code=exited, status=1/FAILURE
time-liquidsoap.service: Failed with result 'exit-code'.
time-liquidsoap.service: Service hold-off time over, scheduling restart.
time-liquidsoap.service: Scheduled restart job, restart counter is at 5.
ed Libretime Liquidsoap Service.
```

**Comment by paddatrapper** [comment]
Is there more above those lines in the logs? You may need to use `jounalctl -xe`

**Pull request closed without merging**
