### PR TITLE
Docs/added database documentation

### PR DESCRIPTION
**Pull request by Robbt**
I decided to document how to add tables to a database and how to use the postage tool to view the database. More documentation coming as I want to provide a rough overview of how LibreTime works for anyone just getting started with it since there are so many moving parts and we have no contact with the original developers. Although we probably need to rewrite the entire manual and update the screenshots etc at some point.

### CODE REVIEW

**Comment by Robbt** [comment]
This needs to be cleaned up to not include the log rotation stuff.

**Comment by hairmare** [comment]
Is this ready to merge? It seems to have fallen through the cracks and I'd like to get it merged before I do the next alpha.

**Comment by Robbt** [comment]
Yes, I think so. I just added some basic documentation about the Database orientated towards developers. 

Do we want to do documentation updates via PR ?

Treating it like a Wiki might make more sense. I was thinking of updating the documentation. I just did a LibreTime training yesterday for another community radio station that will be adopting it here in Columbus as they migrate from Airtime.pro, and I think I should include the Auto Playlist somewhere on the Libretime.org documentation. 

We should also at some point go through and update the screenshots and replace Airtime with LibreTime throughout the text while also documenting the new features we've added.

Is it the proper procedure to do these as PR's or should we just edit the documentation directly. I know being on LibreTime.org it offers the choice to edit directly on GitHub and I can change the markdown directly and commit it. I'm cool with either way, we just need to make a decision I think.

**Comment by hairmare** [comment]
There is also the GitHub Wiki https://github.com/LibreTime/libretime/wiki which is available for edits without a rigid PR process.

I think it makes sense to have changes to the main docs go through a review process. Going forward it might even make sense to start asking for doc updates during review of PRs that add new features.

Having the docs updates in their PRs alsos help ensure that they don't break the mkdocs build by accident.

BTW, you can choose to create a branch when saving the results of edits done through the GitHub webinterface. For those that don't have edit rights on the repo it properly asks where to fork to when saving (this is why the "Edit on GitHub" links on libretime.org make sense). This isn't handy for Maintainers and Administrators since it won't ask to save to a a fork if you have edit rights, you can get around this by editing directly on the fork and not using the mentioned links.

**Pull request merged**
