### PR TITLE
Use python-magic for mime type detection

### LINKED ISSUE #717: `file-magic` newest release
**Describe the bug**
With `file-magic` 0.4.0 which went out live on 1st of Jan 2019
https://pypi.org/project/file-magic/#history
there is an issue that the `airtime_analyzer` no longer works properly:
```
2019-01-23 05:28:42,251 [analyzer_pipeline] [ERROR]  'module' object has no attribute 'open'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 66, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 44, in analyze
    ms = magic.open(magic.MIME_TYPE
```

**To Reproduce**
Install `file-magic == 0.4.0`.

**Expected behavior**
No error should happen or fix `file-magic == 0.3.0` in the `requirements.txt` file.

**LibreTime version:**
`8dd55e2`

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes #717

### CODE REVIEW

**Comment by paddatrapper** [comment]
Ok it is still needed, but the separate handling of wave files can be dropped.

**Comment by paddatrapper** [comment]
The python-magic package in Debian from Buster on has been moved to use [python-magic](https://github.com/ahupp/python-magic) and not file-magic. We're going to run into #166 again soon

**Comment by paddatrapper** [comment]
File-magic was provided by the package python-magic from the source file until stretch. Since Feb 2018, the python-magic package is provided by the same upstream as pypi python-magic and src:file no longer provides a python package

**Comment by paddatrapper** [comment]
I agree this should probably be held back and in the mean time, just require `file-magic<0.4.0` in the `setup.py` script.

The monkey patch would work, though the exact implementation would need to change due to the changes in file-magic 0.4.0 (#717).

**Comment by paddatrapper** [comment]
I have managed to find the [ITP bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877849) which describes some of the actions taken, but not why file-magic dropped the python package... By the looks of things file and python-magic have the same maintainer, who made the decision to move. The compat layer seems to be by design upstream at least.

**Comment by hairmare** [comment]
Thanks for the link, I found this https://github.com/ahupp/python-magic/issues/180 which explains how the compat layer is a branch that integrates the libmagic api into the new python-magic.

This is somewhat dependent on https://github.com/ahupp/python-magic/issues/21 as well since that is where the original [libmagic-compat](https://github.com/ahupp/python-magic/compare/libmagic-compat) branch is from. We should probably wait with changing setup.py until the branch is merged.

I guess our best bet for now is to reply on the compat layer in packages and use the original api in our code. That way it will work both with the new and old packages. WDYT?

**Comment by paddatrapper** [comment]
I think that is a good solution. I'll close this then

**Pull request closed without merging**
