### PR TITLE
Add the ability to ignore postgresql and rabbitmq in the default setup script

### PR DESCRIPTION
**Pull request by ned-kelly**
This is a must have if you're bundling with an automated deployment where the database & rabbitmq are not on the same host (in this use case they are actually living in other docker container's) - The user account creation and default vhost for RMQ is setup in elsewhere and not part of the install script.

Please see the [docker-multicontainer-libretime](https://github.com/ned-kelly/docker-multicontainer-libretime) repo for real world example.

### CODE REVIEW

**Comment by Robbt** [comment]
Hey this looks good. I'll need to review it, but in terms of the ffmpeg processing etc that should be done in a separate PR as it is solving a different problem and one of the guidelines says that PRs should be focused on specific problems and not a bundling of different issues. It makes it easier to go through.

I will try to spend some more time on the docker implementation you are working on.

**Comment by frecuencialibre** [comment]
Hi all, thank you for all this work!!! true blue airwave bushranging. 

I'm sure we at our little community radio station are not alone in needing guidance and modern tooling to get a production server up and running quickly. I wanted to share here my success installing docker-multicontainer-libretime. I haven't started testing it yet, but at least it installed, which is great.

My apologies in advance for my ignorance regarding docker. First, I installed docker-ce and docker-install on debian as per the official instructions [1](https://docs.docker.com/install/linux/docker-ce/debian/) [2](https://docs.docker.com/compose/install/#install-compose). I then chose to stick with default icecast etc. variables, cutting straight to the point:
```
r@rdebian:/var/www/html/docker-multicontainer-libretime$ sudo docker-compose up -d
Creating network "docker-multicontainer-libretime_libretime-internal" with driver "bridge"
ERROR: Network libretime declared as external, but could not be found. Please create the network manually using `docker network create libretime` and try again.
```

so then i'm a good instruction followerer: `sudo docker network create libretime`

and then repeating `sudo docker-compose up -d` seemed to work without errors. :+1:  :+1:  :+1:

**Comment by ned-kelly** [comment]
> Hi all, thank you for all this work!!! true blue airwave bushranging.
> 
> I'm sure we at our little community radio station are not alone in needing guidance and modern tooling to get a production server up and running quickly. I wanted to share here my success installing docker-multicontainer-libretime. I haven't started testing it yet, but at least it installed, which is great.
> 
> My apologies in advance for my ignorance regarding docker. First, I installed docker-ce and docker-install on debian as per the official instructions [1](https://docs.docker.com/install/linux/docker-ce/debian/) [2](https://docs.docker.com/compose/install/#install-compose). I then chose to stick with default icecast etc. variables, cutting straight to the point:
> 
> ```
> r@rdebian:/var/www/html/docker-multicontainer-libretime$ sudo docker-compose up -d
> Creating network "docker-multicontainer-libretime_libretime-internal" with driver "bridge"
> ERROR: Network libretime declared as external, but could not be found. Please create the network manually using `docker network create libretime` and try again.
> ```
> so then i'm a good instruction followerer: `sudo docker network create libretime`
> 
> and then repeating `sudo docker-compose up -d` seemed to work without errors. 👍 👍 👍

Glad you got it working - Just a heads up, the build that you've run is actually running the Libretime fork in my repo which has some changes which are not yet merged back into the main Libretime branch (Hence this PR) - If you're going to pull in a lot of podcasts etc on a schedule (We pull in 30-30 a week) you're going to need to keep an eye on the `/tmp/` directory inside the container and occasionally clean up the files as they are not auto-deleting currently.

Also, this PR is actually to run all podcasts through FFMPEG which will basically convert the filetype - If you don't want all your Podcasts to be in MP3 format it's best to re-build the container against the official Libretime repo). Generally most Podcasts are not in FLAC/AAC anyway so I doubt it's an issue unless your an Audiophile.

**Comment by hairmare** [comment]
The installer updates are now on their own in #517.

I'm using unofficial RPM packages in my [centos based multicontainer dockerfiles](https://github.com/hairmare/centos-docker-libretime) so I haven't been bitten by the needed installer changes.

In the long run, I think we would like to see the installer only be used for it's original use-case, letting users test out latest code to help debug issues while running off of distro packages (or a supported container deployment with docker, lxc, flatpak or something else).

**Comment by Robbt** [comment]
So I'm going to close this for now because I merged the portion of it with #517 that are described in the title. If you want to make a separate PR for converting everything to mp3 with ffmpeg that would make the most sense. I'm not sure that we would want to merge that into core without the option to enable or disable it via the UI though as we haven't made a decision to only support mp3 files in our library.

**Comment by hairmare** [comment]
> only MP3's are currently supported with podcasts for now anyway.

I think that's mostly true but I don't think it was a conscious design decision, my theory is that all the test-cases used during developing the feature only used mp3 so support was never really added. From what I remember the whole podcast-ingesting feature is kind of spaghetti-codey anyway.

**Pull request closed without merging**
