### PR TITLE
docs: update structure and create links between pages

### PR DESCRIPTION
**Pull request by jooola**
This is introduce a solid structure to the documentation, split into 3 parts:
- the Admin manual provide guides and references for administrators to setup and configure LibreTime.
- the User manual provide guides and tutorials for managers, and content creators to use LibreTime.
- the Developer manual provide tools and guides for developers to integrate or improve and contribute to LibreTime.

It also adds links between pages to improve navigation and "take the reader by the hand" in order to walk him through all required (recommended) steps to achieve a specific goal.

This should make the documentation somewhat future proof.

Fixes #1611

### CODE REVIEW

**Comment by jooola** [comment]
I didn't do much change in the developer manual and user manual this should go in another PR.

**Comment by paddatrapper** [comment]
Is there an example somewhere online that we can look at?

**Comment by jooola** [comment]
https://jooola.github.io/libretime/ I guess but I need to fix the website config.

**Comment by jooola** [comment]
Ok, should be working now.

**Comment by paddatrapper** [comment]
The main menu/`Docs` drop-down has a different item ordering to the side menu. The drop-down should probably be

1. Admin
2. User
3. Developer

* Inconsistent capitalization on the Docs side menu (some items have Title Capitalization, while others have Sentence capitalization)
* https://jooola.github.io/libretime/docs/user-manual/ is still todo
* https://jooola.github.io/libretime/docs/developer-manual/ is still todo
* https://jooola.github.io/libretime/docs/releases/unreleased/ - what is the goal with this page?

**Comment by jooola** [comment]
I'll fix the dropdown menu.

> Inconsistent capitalization on the Docs side menu (some items have Title Capitalization, while others have Sentence capitalization)

We have a linter for this, but I haven't renamed all the title yet; I could do the change in this PR, but I tried to keep the change focused to the admin manual.

> https://jooola.github.io/libretime/docs/user-manual/ is still todo
> https://jooola.github.io/libretime/docs/developer-manual/ is still todo

Yes, it is, do accept having such todo in the documentation while work is on progress ? These entry point should be handled once the user manual or developer manual are updated, which should be handled in another PR as I mentioned earlier. If we are of with packing everything in a single PR I will keep on working on this. I just don't want to make this PR a too big milestone either.

> https://jooola.github.io/libretime/docs/releases/unreleased/ - what is the goal with this page?

The idea is to have a file we can fill with details while adding features to the main branch. To reduce the amount of work at the release moment. This file could be private by prepending a `_` and we would simply have to copy/paste to the final version file.

**Comment by paddatrapper** [comment]
> We have a linter for this, but I haven't renamed all the title yet; I could do the change in this PR, but I tried to keep the change focused to the admin manual.

No, can be a separate PR

> Yes, it is, do accept having such todo in the documentation while work is on progress ? These entry point should be handled once the user manual or developer manual are updated, which should be handled in another PR as I mentioned earlier. If we are ok with packing everything in a single PR I will keep on working on this. I just don't want to make this PR a too big milestone either.

What needs updating? The docs have been updated to reflect LibreTime instead of Airtime in content and images.

> The idea is to have a file we can fill with details while adding features to the main branch. To reduce the amount of work at the release. This file could be private by prepending a _ and we would simply have to copy/paste to the final version file.

Wouldn't those details be pulled from the commit messages by semantic-release and rendered through that?

**Comment by jooola** [comment]
> No, can be a separate PR

I update the pages titles, but the content headings will be updated later.

> What needs updating? The docs have been updated to reflect LibreTime instead of Airtime in content and images.

I haven't started working on it so I don't know yet, but I had the plan to add some extra ordering in the different user manuals pages (same for the developer, as I already see 2 category: integrations and contributions).

I want to make the documentation easier to read. To split guides from tutorials, and build some kind of path between the pages. If the docs are difficult to browse/read/understand, it won't be used.

The admin manual is not yet fully done, but I hoped to first introduce this docs layout and then keep improving the documentation, but I guess we can pack everything here.

To answer you specific comment, I think a lot need to be updated to reflect the current usage of LibreTime, for instance I found documentation about a api_client.cfg file that was used to configure the api_client, but that seem outdated, at least I haven't found code responsible for such behavior. In addition the reverse proxy documentation is really poor, as should receive particular attention at I think it is important to use a reverse proxy for such application, at least for ssl termination.

> Wouldn't those details be pulled from the commit messages by semantic-release and rendered through that?

I tried to generated a changelog from the current history (*alpha.10 to HEAD), but the output is not quiet what I expected. So I though we should generate a changelog, and also write a release note that extract some main changes and breaking changes upgrade procedure form the changelog.

**Comment by jooola** [comment]
I am happy to finalize the work in the admin manual, but I would prefer to not do content changes in the user-manual and developer manual for now.

**Comment by paddatrapper** [comment]
> The admin manual is not yet fully done, but I hoped to first introduce this docs layout and then keep improving the documentation, but I guess we can pack everything here.

No, I think the content changes should be a separate PR. I'm happy to merge this as is then

**Comment by paddatrapper** [comment]
Ah just realised that this needed the doc build changes reverted...

**Comment by jooola** [comment]
Ok, this has been merged too fast, could we revert ? I wanted to properly squash the history, to preserve the git history.

**Comment by paddatrapper** [comment]
I have squashed the git history in the merge already

**Comment by jooola** [comment]
Yes, but file renames and content change are in the same commit, and for files with too much changes git cannot identify a file rename.

**Pull request merged**
