### PR TITLE
chore: revert setuptools <64.0.0 pinning

### PR DESCRIPTION
**Pull request by jooola**

### CODE REVIEW

**Comment by jooola** [comment]
upstream issue might be https://github.com/PyCQA/pylint/issues/7306

**Comment by paddatrapper** [comment]
I assume they fixed the cause of #2043 in a later version, so this should probably blacklist 64.0.0?

**Comment by jooola** [comment]
> I assume they fixed the cause of https://github.com/libretime/libretime/issues/2043 in a later version, so this should probably blacklist 64.0.0?

I was wrong saying 64.0.0 breaks the editable install, it only break pylint that raises an import error. The code is working, but pylint does not. I trusted pylint on this one and said everything is broken.

So only have to wait for pylint to handle the pep660 editable install and not raise this editable install error.

**Comment by jooola** [comment]
I think we can work around this by forcing the legacy-editable feature in setuptools. We should be notified once https://github.com/PyCQA/pylint/issues/7306 is resolved.

Ready to be merged.

**Pull request merged**
