### PR TITLE
Travis rewrite

### LINKED ISSUE #1039: Our Travis CI setup is broken
Currently our Travis CI tests a matrix of PHP and Python versions and then uses the artefacts from the python build to deploy to libretime.org. Due to issues with mkdocs, the artefacts are no longer built (#1038). We need to overhaul our travis CI setup to act more like a pipeline:

1. Concurrently run all tests (PHP and Python)
1. Deploy docs on master
1.  Deploy release artefacts on tags

Each stage should be completely separate from each other and not try use the artefacts from the previous stage. I have no idea how to set that up in Travis (GitLab CI built this way by default, so that is all I have used)

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes #1039

Breaks up testing and deploy. This way deploy only happens on successful tests and PRs are not broken by any deploy stage stuff breaking

### CODE REVIEW

**Comment by paddatrapper** [comment]
This also added testing for various Python versions, resulting in #1041

**Comment by Robbt** [comment]
Why don't I see any travis jobs being ran for the commits on this PR ?

**Comment by paddatrapper** [comment]
They definitely have been running... They're what I used to get this done

**Comment by paddatrapper** [comment]
I'll see what the issue is tomorrow

**Comment by paddatrapper** [comment]
Just needed a force push. Travis has ran successfully now

**Comment by paddatrapper** [comment]
Fixed the merge conflict

**Pull request merged**
