### PR TITLE
feat: flush db stream settings data

### PR DESCRIPTION
**Pull request by jooola**
Remove data that has been deprecated in #1986

Migration filename will need renaming.

### CODE REVIEW

**Comment by jooola** [comment]
Should we schedule this for 3.0.0 or 3.1.0 ?

**Comment by paddatrapper** [comment]
Release next+1

**Comment by jooola** [comment]
I think we should stop versioning the legacy schema with the libretime version. We cannot guess which version number will be next. Maybe we should use dates, `20221010.0.1`

**Comment by paddatrapper** [comment]
Can do either date or just numerical increments

**Comment by jooola** [comment]
Yes, you are right, we will use the same number as the migration file prefix

**Comment by jooola** [comment]
Done, this is ready.

**Pull request merged**
