### PR TITLE
feat: drop distros support

### PR DESCRIPTION
**Pull request by jooola**
So here a big cleanup, but I was wondering if we want to split this into multiple PRs ?

### CODE REVIEW

**Comment by jooola** [comment]
I'll force a CI run on each commit and slowly stack them in this branch.

**Comment by jooola** [comment]
This is ready to be merged.

**Comment by paddatrapper** [comment]
Yay for cleaner code :tada:

**Comment by jooola** [comment]
We deprecated python 3.7 but I didn't drop it as I am unsure if we should bump the python version to >=3.8. The only reason would be to keep backward compatibility for people that have custom system, so advanced users.

We are not a library so I would go for raising the minimal version to 3.8, and follow our deprecation notice.

**Comment by paddatrapper** [comment]
That is reasonable. I agree we should drop it

**Pull request merged**
