### PR TITLE
feat(analyzer): rework analyze_metadata step

### LINKED ISSUE #717: `file-magic` newest release
**Describe the bug**
With `file-magic` 0.4.0 which went out live on 1st of Jan 2019
https://pypi.org/project/file-magic/#history
there is an issue that the `airtime_analyzer` no longer works properly:
```
2019-01-23 05:28:42,251 [analyzer_pipeline] [ERROR]  'module' object has no attribute 'open'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 66, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 44, in analyze
    ms = magic.open(magic.MIME_TYPE
```

**To Reproduce**
Install `file-magic == 0.4.0`.

**Expected behavior**
No error should happen or fix `file-magic == 0.3.0` in the `requirements.txt` file.

**LibreTime version:**
`8dd55e2`

### PR DESCRIPTION
**Pull request by jooola**
- Upgrade mutagen to 1.45.1
- Remove custom wave data extraction
- Add .wav fixtures
- Move md5 sum in it's own function
- Cleanup comments
- Let analyze_cuepoints handle cuein and cueout metadata

Close #717

### CODE REVIEW

**Comment by jooola** [comment]
Related to #1592

**Comment by jooola** [comment]
I wonder if we need our own mime type guessing function as mutagen already handle this ? I don't want to break anything so I leave it as it is.

**Comment by jooola** [comment]
I removed the magic mime type guessing, I can revert if we want to be conservative. But I feel it is only needed to guess the mime type of file other than audio files, which seem unnecessary.

**Comment by paddatrapper** [comment]
Yeah, best to remove that. You can see the discussion on #719 about the issues we encountered with it.

**Comment by jooola** [comment]
Ok removed the magic thing and squashed everything clean, it ready to be reviewed and merged.

**Pull request merged**
