### PR TITLE
Migrating docs to @ned-kelly's bootstrap theme

### PR DESCRIPTION
**Pull request by zklosko**
Commencing operation: avenge @ned-kelly! 🦸‍♂️ 

This PR will add @ned-kelly's one page theme to our Jekyll site. In addition to the splash page, I am working on extending it based on the theme that was created (note: some of the auto-scrolling was taken out). Some of the docs will also be updated, merged, and deleted as necessary to reflect the latest features of LibreTime.

```
/docs
  - /css
  - /_data
  - /_layouts
  - /_includes
  - index.md
  - docs...
```

The raw code of theme is being merged by hand since Github Pages wasn't able to recognize the remote theme in my repo. Progress can be examined [here](https://zklosko.github.io/libretime). This will solve #333, #1029, #1025, and #1049, and picks up where #590 left off.

### CODE REVIEW

**Comment by zklosko** [comment]
Still a work in progress, but requesting review from @Robbt and @paddatrapper

**Comment by paddatrapper** [comment]
Looks very good! I'll try review it more extensively tomorrow

**Comment by paddatrapper** [comment]
Looks good! My comments:

- The images in the Key features section of the front page link to the screenshot image. Perhaps these should link to the manual page that they refer to?
- Preparing the Server occurs both in https://zklosko.github.io/libretime/preparing-the-server and https://zklosko.github.io/libretime/quickstart. Perhaps it should be left in Preparing the Server and modify the note in Quickstart to link to preparing the server as an explanation of how to configure those requirements
- https://zklosko.github.io/libretime/live-broadcast - make the YT video more obviously a YT video. In #811, @Robbt was unable to embed, which is why we have the screenshot stuff that is currently there. Is it possible to embed with the new site?
- https://zklosko.github.io/libretime/dashboard - The Tracks, Playlists, etc links return 404. e.g. https://zklosko.github.io/tracks
- https://zklosko.github.io/libretime/troubleshooting - the final command needs formatting as a command (`rabbitmqctl ...`). Also need to check if the Test tones section actually still exists
- https://zklosko.github.io/libretime/interface-customization - doesn't have the contents right panel
- https://zklosko.github.io/libretime/icecast-shoutcast - doesn't have the contents right panel
- https://zklosko.github.io/libretime/hd-audio-modules - doesn't have the contents right panel
- https://zklosko.github.io/libretime/uninstall - doesn't have the contents right panel
- Missing links to some pages e.g. Reverse Proxy docs (haven't done an exhaustive check for others)
- Open Sponsor link in new tab

**Comment by zklosko** [comment]
@paddatrapper 
>     * The images in the Key features section of the front page link to the screenshot image. Perhaps these should link to the manual page that they refer to?

I'm not sure what you're referring to. The link in the orange section of the front page scrolls to the features blurb on the same page.

>     * Preparing the Server occurs both in https://zklosko.github.io/libretime/preparing-the-server and https://zklosko.github.io/libretime/quickstart. Perhaps it should be left in Preparing the Server and modify the note in Quickstart to link to preparing the server as an explanation of how to configure those requirements

Noted. I'm removing Preparing the Server from the navigation for now.

>     * https://zklosko.github.io/libretime/live-broadcast - make the YT video more obviously a YT video. In #811, @Robbt was unable to embed, which is why we have the screenshot stuff that is currently there. Is it possible to embed with the new site?

It's very possible. Fixed. 

>     * https://zklosko.github.io/libretime/interface-customization - doesn't have the contents right panel
> 
>     * https://zklosko.github.io/libretime/icecast-shoutcast - doesn't have the contents right panel
> 
>     * https://zklosko.github.io/libretime/hd-audio-modules - doesn't have the contents right panel
> 
>     * https://zklosko.github.io/libretime/uninstall - doesn't have the contents right panel

Oops. Fixed.

>     * Open Sponsor link in new tab

There isn't a way to do it in markdown, and doing it in HTML breaks with the style of the navbar on top.

I haven't looked at the other items yet. I also deleted all of the Airtime screenshots in one fell swoop, so the site is about to have a lot less images. I'll replace them when I get the chance.

**Comment by paddatrapper** [comment]
> I'm not sure what you're referring to. The link in the orange section of the front page scrolls to the features blurb on the same page.

Under the 'Key features include' heading there is a grid of pictures. When you hover over them they describe different features (e.g. Intelligent Library and Streaming Listener Statistics). These images are clickable, but only open the image itself, which doesn't make much sense. I'm suggesting rather change that link to be something more useful like the relevant section of the docs

**Comment by zklosko** [comment]
@paddatrapper I'm still missing images but I've worked in most of your changes. Please review when you get the chance.

**Comment by paddatrapper** [comment]
* Intelligent Library image still links to the jpeg on the front page, I like the rest of the links though
* https://zklosko.github.io/libretime/vagrant - Title and note spelling error 'VirtualBox' also the heading links are not rendering correctly: `(Ubuntu and Debian)[#Ubuntu and Debian]`, remove the references to mkdocs in the last section about provision targets
* https://zklosko.github.io/libretime/scheduling-shows - Can there be a space between the bottom of the title and the top of the YoutTube embed?
* Docs link should probably link to Installing or Using LT rather than contributing back to it
* https://zklosko.github.io/libretime/host-configuration - has quick links, but some other pages do not. Maybe all should have for consistency?
* https://zklosko.github.io/libretime/ota-broadcast - this just links to the UNESCO guide. Is there more to come here? I think the graphics on the different LT architectures (at the bottom of https://libretime.org/features) may be appropriate

**Comment by zklosko** [comment]
The `ota-broadcast` page is going to take some time to be filled out, so I'm okay if we merge before it's finished.

**Comment by zklosko** [comment]
@paddatrapper Please review

**Comment by paddatrapper** [comment]
- The introduction link in the header doesn't make a lot of sense to me - you already link back to the home page through the 'LIBRETIME' title link, so why have a second one?
- The Docs header link links to https://zklosko.github.io/libretime/scheduling-shows which seems a bit random. Maybe link to https://zklosko.github.io/libretime/quickstart instead
- https://zklosko.github.io/libretime/vagrant - missing the right-hand table of contents, spelling error in prerequisites: `VirturalBox`
- https://zklosko.github.io/libretime/quickstart - Configuring Track Types links to https://zklosko.github.io/libretime/track-types, which is 404
- The quicklinks section for section links loads the page with the heading just above the visible text, thus cutting it off. It would be better to have it render from slightly higher up, so that the header is displayed to guide the user's eye
- https://zklosko.github.io/libretime/library - no screenshots. Not sure if that is intended or not, screenshots 404
- https://zklosko.github.io/libretime/microsite - screenshot 404
- https://zklosko.github.io/libretime/users - screenshot 404
- https://zklosko.github.io/libretime/playlists-smartblocks - screenshot 404
- https://zklosko.github.io/libretime/playout-history - screenshot 404
- https://zklosko.github.io/libretime/podcasts-webstreams - screenshot 404
- https://zklosko.github.io/libretime/preparing-media - weird formatting in the final paragraph, screenshots 404
- https://zklosko.github.io/libretime/scheduling-shows - screenshots 404
- https://zklosko.github.io/libretime/settings- screenshots 404
- https://zklosko.github.io/libretime/listener-stats - screenshot 404
- https://zklosko.github.io/libretime/backing-up-the-server - last paragraph, the `(` is included in the text for the links to rsync and rdiff-backup
- https://zklosko.github.io/libretime/icecast-shoutcast - Source Configuration screenshot - 404
- https://zklosko.github.io/libretime/unesco-guide - maybe remove the last paragraph
- https://zklosko.github.io/libretime/live-broadcast - 404 screenshots
- https://zklosko.github.io/libretime/troubleshooting - RabbitMQ commands in the steps need monospace formatting
- https://zklosko.github.io/libretime/host-configuration - has quick links, but some other pages do not. Maybe all should have for consistency?

Missing docs:
- https://libretime.org/exporting-the-schedule
- https://libretime.org/reverse-proxy
- https://libretime.org/intro-playlist
- https://libretime.org/autodj
- https://libretime.org/outro-playlist

**Comment by zklosko** [comment]
@paddatrapper I'm so sorry, I sent the "please review" before I remembered that I had deleted most of the images.

The reverse proxy doc is hiding; I'll change that.

The rest of the missing docs you mentions have been merged into other docs.

School and coverage of the Black Lives Matter protests have really been bogging me down. I'll see if I can finish up this week. Thanks.

**Comment by zklosko** [comment]
To everyone: I really need help working on this. The documentation heavily favors Linux users, which will probably not help most of our users. Tools need to be mentioned for Windows and Mac users too. There's also a lot of screenshots and it isn't always clear what features still exist/are worth mentioning.

**Comment by Robbt** [comment]
So what do you specifically need help with ? Do you need screenshots taken for the pages where they are missing ?

I'm not sure what specific pages from the documentation you want to remove or have externally. 

Also the UNESCO radio guide seems cool but it also appears to have a copyright so we might just want to link to the UN library so people can download it vs. distributing the PDF ourselves - https://unesdoc.unesco.org/ark:/48223/pf0000156197

I've been pretty absent but I can try to put some time in this week to help move this along. It is looking good thus far.

**Comment by zklosko** [comment]
@Robbt I need help with screenshots, rewriting 90% of the site, and wrestling with the theme's HTML. It doesn't have all of the features we need for a docs site out of the box.

**Comment by paddatrapper** [comment]
> To everyone: I really need help working on this. The documentation heavily favors Linux users, which will probably not help most of our users. Tools need to be mentioned for Windows and Mac users too.

What tools are missing? Mixxx, Butt and quodlibet are all cross-platform. What other tools do we mention?

>  There's also a lot of screenshots and it isn't always clear what features still exist/are worth mentioning.

Unless mentioned in #376, the features should still work. In terms of worth mentioning - if users will use it, we should probably mention how to do it.

**Comment by zklosko** [comment]
Installation instructions are more written for Linux users. The programs on the Preparing Media page are more for Linux.

I'm not sure, there's just so much documentation.

**Comment by paddatrapper** [comment]
The thing about installation is that we only support Linux... I have never used Windows Server and have no idea if our software will even run there.

The Preparing Media page programs all run on Linux, Windows and Mac, except for the Audio Loudness section. We should probably find something cross-platform for there...

There is a lot. Maybe we should rather have a docs sub-site that is structured more like Read The Docs with the main site being more of an overview and containing what is in this PR?

**Comment by zklosko** [comment]
> The thing about installation is that we only support Linux... I have never used Windows Server and have no idea if our software will even run there.

We might run on WSL but I'd still strongly recommend using Linux to power Libretime. If anything else, Linux over Windows Server will significantly lower the cost of deployment.

**Comment by zklosko** [comment]
@paddatrapper @Robbt I made some theming updates. Could you please take a look and let me know what you think about the direction I'm going? There still are a lot of missing images, some due to a bug I'm working on (they displayed locally with `jekyll serve` but wouldn't display on the GitHub-compiled site.

**Comment by paddatrapper** [comment]
Looks good! My one comment would be that install (https://zklosko.github.io/libretime/install) has 'Back to Docs' link, but the guides page which that links to doesn't have a link to the install page, which seems weird to me.

Another note is that on small screens, the right-hand contents list is rendered half off-screen. Maybe they should be under a hamburger menu or a collapsed div at the top of the content on smaller screens?

**Comment by zklosko** [comment]
> Another note is that on small screens, the right-hand contents list is rendered half off-screen. Maybe they should be under a hamburger menu or a collapsed div at the top of the content on smaller screens?

There absolutely should be! That's my next project.

**Comment by zklosko** [comment]
@paddatrapper Please review :D

**Comment by paddatrapper** [comment]
* https://zklosko.github.io/libretime/vagrant - The heading links are not rendering correctly: (Ubuntu and Debian)[#Ubuntu and Debian]
* The examples at the bottom of https://libretime.org/features are missing

This PR re-enables self-hosting the docs right? In that case they need to be re-added to the Vagrant file and to the Vagrant docs. Also what changes are required to get these to publish to Github pages?

**Comment by zklosko** [comment]
I deliberately removed the examples from the bottom of /features because I think it's too complicated. I'd like to see newer, simpler drawings in its place, especially because radio station admins may not be as familiar with Liquidsoap or the Linux system process structure.

**Comment by zklosko** [comment]
> This PR re-enables self-hosting the docs right? In that case they need to be re-added to the Vagrant file and to the Vagrant docs. Also what changes are required to get these to publish to Github pages?

Yes, the PR continues to allow users to self-host the docs. The only change required to get it to publish is to merge the PR into the master branch. I'm not sure what you mean by adding it to the Vagrant file; it should be okay with the last one and it would be easier to host jekyll running on the host's desktop instead of a VM so that the files can be edited.

**Comment by paddatrapper** [comment]
> I'm not sure what you mean by adding it to the Vagrant file

https://github.com/LibreTime/libretime/commit/d7ee6a6f4c641608e763dff54d5896d6dd5b6aca#diff-23b6f443c01ea2efcb4f36eedfea9089R74-R75

These need uncommenting and the scripts and names updating

**Comment by paddatrapper** [comment]
> I deliberately removed the examples from the bottom of /features because I think it's too complicated. I'd like to see newer, simpler drawings in its place, especially because radio station admins may not be as familiar with Liquidsoap or the Linux system process structure.

Ok. Is this a TODO for after merge or a requirement for merging?

**Comment by zklosko** [comment]
I was going to say TODO after merge. I'm about to get clobbered with schoolwork and I want y'all to enjoy your shiny new site.

**Comment by zklosko** [comment]
I know there's an issue with Github Pages rendering my repo site because the CNAME file got accidentally committed, but can we still merge this PR? It shouldn't affect the site once it's in the Libretime repo.

**Comment by Robbt** [comment]
Cool everything looks good still if you just append libretime onto the URL of your demo site. I think we could go forward with merging this, it's a dramatic improvement over the 1st and even current site.

**Comment by zklosko** [comment]
Done.

**Comment by paddatrapper** [comment]
I've merged. Please check that the site looks as expected

**Comment by zklosko** [comment]
The scroll to top button doesn't work on half the site, which is odd because it worked during local development. I can fix that in a future PR. Otherwise, the site looks good!

**Pull request merged**
