### PR TITLE
Problem: LibreTime needs initializing

### PR DESCRIPTION
**Pull request by hairmare**
Solution: I am initializing this repo as per our discussions on [the LibreTime taiga](https://tree.taiga.io/project/robbt-libreairwaves-airtime-fork).

### CODE REVIEW

**Comment by hairmare** [comment]
Thanks for merging. That was what I was waiting for :)

**Comment by hairmare** [comment]
Feel free to merge others as well if you think they look good.

**Comment by Robbt** [comment]
Ok, so what is the proper procedure for review. I know we don't have unit testing integrated at this point. Should I still try to have a test instance up where I can pull in the commit and make sure there aren't any syntax errors or what not ? Or is a simple code review sufficient at this point. I've started to look at them but I don't want to jump the gun if we are expecting a more thorough process for approval.

Also what is the procedure for me putting the work I did on my original branch into a pull request (I have never really played the role of admin on of a functional github project before). I have some ideas, I noticed you are created new branches for features and then making a pull request and closing the branch afterwards. Is this explained in the C4 (if so I can reference that). Otherwise any pointers on how to do this would be helpful. I can read git tutorials on the subject matter but I would be just as happy to follow your lead for now in terms of emulating your process.

**Comment by hairmare** [comment]
I was just working at fixing unit testing :) For now, I plan on doings simple code review for small enough changes and more through tests on larger changesets.

If everything works out with fixing unit-testing, we can run the tests through travis and they will also help with reviews.

The C4 doesn't really have much to go by. I created my fork due to the following passage:

> The project SHALL NOT use topic branches for any reason.  Personal forks MAY use topic branches.

The *MAY* part makes this optional, for me having topic branches helps me bundle things that go together and then rebase/squash them before creating a PR. I also feel those are easier to review and are also in the spirit of:

> A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem.

The last one is a *SHOULD*, so not strictly mandated at all times. I it preferable due to the reasons outlined above.

Locally I have my fork set up as `origin` remote and the master repo set up as `upstream` remote. I usually base my feature branches directly off of `upstream/master` and I also make heavy use of rebasing before I do a PR. There is no provision that mandates this in C4 which makes sense since it is advanced git-fu.

One thing that usually really helps me get things to look the way I want is to visualize the git tree using `gitk` or something similar before pushing.

**Pull request merged**
