### PR TITLE
Feature/repeat autoplaylist until show is full

### PR DESCRIPTION
**Pull request by Robbt**
This is a simple test of the functionality, need to make it an option vs always on which will require modifying the DB. Considering if additional UI additions would be useful as well. Just putting this up for feedback and testing at this point.This addresses #119

### CODE REVIEW

**Comment by Robbt** [comment]
It looks like the tests are failing because of the database update. Any idea how to fix this ?

**Comment by hairmare** [comment]
I think you need to add them to AirtimeUpgrader300alpha1 instead of creating a new AirtimeUpgrader300alpha2 (alpha2 one is only needed after we release alpha1). Although that shouldn't matter since tests always re-initialize the complete database.

Most likely the issue is that the new field is missing from `airtime_mvc/build/schema.xml`. Using that file is the proper way to add new fields. You add them in there and then `cd dev_tools/ && bash propel_regenerate.sh`. This also updates all the CcBase* classes so you don't need to change them manually.

**Comment by Robbt** [comment]
Ok when trying to run the propel regenerate I'm getting permission denied line 50 even when running as sudo or root - both from inside the vagrant box and outside of it - line 50 is     $args = isset($argv) ? $argv : $_SERVER['argv']; // $_SERVER['argv'] seems to not work (sometimes?) when argv is registered

**Comment by Robbt** [comment]
Ok, quick question, the upgrade function isn't upgrading the database automatically probably because master was already considered 3.0.alpha.1 thus it didn't trigger a new version. 

I suppose in order to test it on an existing install someone will just need to manually modify the database to add the column. Is there an easier way to handle this ?

**Comment by hairmare** [comment]
True, the update doesn't get automatically triggered when it already had some contents and we just added more. I usually go for a destroy & up to test these (and I've also done them manually as well). In theory it should also be possible to downgrade re-upgrade the database using `utils/upgrade.py`.

On the other hand the db version has matched the libretime version in the past. I'm not quite sure how this was solved in the past. One way to get around this would be to do releases more often.

All in all I think we need to live with the fact that the database might get hosed after a merge. The worst case scenario I can come up with is that we merge a DB change and then realize that it needs reverting before it makes it into a release.

**Comment by Robbt** [comment]
Ok, so this code needs more work, there is an issue where it gives an exception because it doesn't like to add a playlist immediately after it added a playlist. 

2017-03-31T21:59:57+00:00 INFO (6): localhost ts 1490997474 last sched 1490997596
2017-03-31T21:59:57+00:00 ERR (3): localhost [ErrorController.php:26 - errorAction()] - The show Untitled Show has been previously updated!
2017-03-31T21:59:57+00:00 ERR (3): localhost [ErrorController.php:27 - errorAction()] - #0 /vagrant/airtime_mvc/application/models/Scheduler.php(1054): Application_Model_Scheduler->validateRequest(Array, true)

I'm also not sure percent scheduled works as I intended it too. 
Right now I have 800 hours worth of programming scheduled for a show that was cancelled and it is still playing the first 5 seconds of every track. So there is some sort of bug there as well. I can't look at the Pypo logs since they don't exist, but just a note for future digging as this may be related to other issues.

**Comment by hairmare** [comment]
The first 5 seconds issue could be related to #46 and/or #125. I think the easiest way to see what pypo is doing is to stop the service and start it manually, what should be in the logs turns up on stdout/stderr.

**Comment by Robbt** [comment]
Yeah, I think I just seriously overloaded liquidsoap - I can't say it is directly related to either of them - here is what happened with airtime-playout manually started
```
2017-03-31 22:59:57,948 [pypofetch] [INFO ]  Handling command: update_schedule
2017-03-31 22:59:58,487 [pypoliquidsoap] [INFO ]  Need to add items to Liquidsoap *now*: set([13312, 13314, 13316, 13318, 13320, 13322, 13324, 13326, 13328, 13330, 12308, 13334, 13336, 13338, 13340, 13342, 12320, 13346, 13348, 12326, 12328, 13354, 12332, 13358, 13360, 13362, 12340, 13366, 13368, 13370, 13372, 12350, 13376, 13378, 13380, 13382, 13384, 13386, 12364, 13390, 13392, 13394, 13396, 13398, 12376, 13402, 13404, 13406, 13408, 13410, 13412, 12390, 12392, 12398, 12400, 13332, 12414, 12416, 12426, 12434, 12438, 12458, 12470, 13344, 12482, 12488, 12492, 12504, 12506, 12508, 12516, 13350, 12522, 12526, 13352, 12530, 12536, 12542, 12544, 12550, 13356, 12554, 12556, 12558, 12560, 12566, 12568, 12570, 12574, 12578, 12582, 12586, 12590, 12592, 12594, 12596, 12598, 13364, 12602, 12606, 12610, 12612, 12620, 12628, 12632, 12634, 12636, 12638, 12642, 12644, 12648, 12652, 12658, 13374, 12662, 12664, 12666, 12668, 12670, 12674, 12676, 12678, 12680, 12682, 12684, 12688, 12694, 12698, 12700, 12706, 12710, 12714, 12716, 12718, 12720, 12724, 12726, 12732, 12740, 12742, 12744, 13388, 12750, 12752, 12758, 12764, 12766, 12768, 12770, 12774, 12778, 12780, 12782, 12786, 12788, 12792, 12794, 12796, 12798, 12800, 12802, 12808, 12810, 12812, 12814, 12816, 13400, 12818, 12820, 12822, 12824, 12826, 12828, 12830, 12832, 12834, 12836, 12838, 12840, 12842, 12846, 12848, 12850, 12852, 12854, 12856, 12858, 12862, 12866, 12868, 12870, 12872, 12874, 12876, 12878, 12880, 12882, 12884, 12886, 12888, 12890, 12892, 12894, 12896, 12898, 12900, 12902, 12904, 12906, 12908, 12910, 12912, 12914, 12916, 12918, 12920, 12922, 12924, 12926, 12928, 12930, 12932, 12934, 12936, 12938, 12940, 12942, 12944, 12946, 12948, 12950, 12952, 12954, 12956, 12958, 12960, 12962, 12964, 12966, 12968, 12970, 12972, 12974, 12976, 12978, 12980, 12982, 12984, 12986, 12988, 12990, 12992, 12994, 12996, 12998, 13000, 13002, 13004, 13006, 13008, 13010, 13012, 13014, 13016, 13018, 13020, 13022, 13024, 13026, 13028, 13030, 13032, 13034, 13036, 13038, 13040, 13042, 13044, 13046, 13048, 13050, 13052, 13054, 13056, 13058, 13060, 13062, 13064, 13066, 13068, 13070, 13072, 13074, 13076, 13078, 13080, 13082, 13084, 13086, 13088, 13090, 13092, 13094, 13096, 13098, 13100, 13102, 13104, 13106, 13108, 13110, 13112, 13114, 13116, 13118, 13120, 13122, 13124, 13126, 13128, 13130, 13132, 13134, 13136, 13138, 13140, 13142, 13144, 13146, 13148, 13150, 13152, 13154, 13156, 13158, 13160, 13162, 13164, 13166, 13168, 13170, 13172, 13174, 13176, 13178, 13180, 13182, 13184, 13186, 13188, 13190, 13192, 13194, 13196, 13198, 13200, 13202, 13204, 13206, 13208, 13210, 13212, 13214, 13216, 13218, 13220, 13222, 13224, 13226, 13228, 13230, 13232, 13234, 13236, 13238, 13240, 13242, 13244, 13246, 13248, 13250, 13252, 13254, 13256, 13258, 13260, 13262, 13264, 13266, 13268, 13270, 13272, 13274, 13276, 13278, 13280, 13282, 13284, 13286, 13288, 13290, 13292, 13294, 13296, 13298, 13300, 13302, 13304, 13306, 13308, 13310])
2017-03-31 22:59:58,495 [pypofetch] [INFO ]  New timeout: 480
2017-03-31 22:59:58,500 [pypofetch] [INFO ]  Loop #2
2017-03-31 22:59:58,639 [pypopush] [ERROR]  Pypo Push Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/pypopush.py", line 148, in run
    try: self.main()
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/pypopush.py", line 80, in main
    self.pypo_liquidsoap.verify_correct_present_media(currently_playing)
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/pypoliquidsoap.py", line 180, in verify_correct_present_media
    self.play(i)
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/pypoliquidsoap.py", line 33, in play
    self.handle_file_type(media_item)
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/pypoliquidsoap.py", line 61, in handle_file_type
    available_queue = self.find_available_queue()
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/pypo/pypoliquidsoap.py", line 94, in find_available_queue
    raise NoQueueAvailableException()
NoQueueAvailableException

```

**Comment by Robbt** [comment]
And 2017-03-31 22:59:50,285 [pypofile] [INFO ]  copying from http://localhost:8080//rest/media/4 to local cache /var/tmp/airtime/pypo/cache/scheduler/4.mp3
2017-03-31 22:59:50,285 [pypofile] [ERROR]  http://localhost:8080/rest/media/4/download
2017-03-31 22:59:50,466 [pypofile] [INFO ]  copying from http://localhost:8080//rest/media/3 to local cache /var/tmp/airtime/pypo/cache/scheduler/3.mp3
2017-03-31 22:59:50,467 [pypofile] [ERROR]  http://localhost:8080/rest/media/3/download
2017-03-31 22:59:50,732 [pypofile] [INFO ]  copying from http://localhost:8080//rest/media/8 to local cache /var/tmp/airtime/pypo/cache/scheduler/8.mp3
2017-03-31 22:59:50,740 [pypofile] [ERROR]  http://localhost:8080/rest/media/8/download
2017-03-31 22:59:50,947 [pypofile] [INFO ]  copying from http://localhost:8080//rest/media/5 to local cache /var/tmp/airtime/pypo/cache/scheduler/5.mp3
2017-03-31 22:59:50,947 [pypofile] [ERROR]  http://localhost:8080/rest/media/5/download
2017-03-31 22:59:51,135 [pypofile] [INFO ]  copying from http://localhost:8080//rest/media/6 to local cache /var/tmp/airtime/pypo/cache/scheduler/6.mp3
2017-03-31 22:59:51,135 [pypofile] [ERROR]  http://localhost:8080/rest/media/6/download

**Comment by Robbt** [comment]
Ok, while staring at the code I realized that the playlist will always add itself to the beginning of a show based upon how it is programmed. This isn't too surprising considering I resurrected this function from being commented out when I coded the autoplaylist functionality.

**Comment by Robbt** [comment]
Ok, I've finally figured this all out. I fix the AddPlaylistToShow function to actually add to the end of already scheduled tracks and realized I needed to instantiate a new show instance for each add to properly check the percentage and to make it work. This is a little bit of a round about way to do it but it should be working.

**Comment by korotkov13** [comment]
after upgrading I have OOPS page, after login.

**Comment by korotkov13** [comment]
after making clean install and restoring db, it works again.

**Comment by hairmare** [comment]
Sorry about that, we haven't quite figured out how to make db changes that happen in between a release comfortable. 

In theory it should be possible to downgrade to `utils/python upgrade.py --downgrade && utils/python upgrade.py` but that doesn't work right now 😞  Another option would be to execute `ALTER TABLE cc_show ADD COLUMN autoplaylist_repeat boolean default 'f' NOT NULL;` directly on the database.

**Pull request merged**
