### PR TITLE
chore: release 3.0.0-beta.0

### PR DESCRIPTION
**Pull request by jooola**
- #1471
- #2096
- #2153
- #2107

### CODE REVIEW

**Comment by jooola** [comment]
Should we start maintain only a single version of the docs ? Or at least only for v3.0.x ?

The current main branch is running in production and staging. I haven't seen any new bugs yet.

I'll test:
- fresh installs for bionic and bullseye on vagrant
- fresh docker install,
- migrate from alpha.13 to beta.0

After that I think we are ready to publish 3.0.0-beta.0.

@paddatrapper Would you have some time for testing or should I do this on my own ? With that said, until we release 3.0.0, I expect to release betas often to provide quick fixes to bugs, so we can always fix afterwards.

**Comment by jooola** [comment]
@paddatrapper When ready I will need your approval for this release. I was hoping to release this today, is that ok for you ?

**Comment by paddatrapper** [comment]
I'm out this evening. So I'll only be able to look at things tomorrow morning unfortunately

**Comment by paddatrapper** [comment]
I've done some testing in Vagrant. Looks good to me to release

**Comment by jooola** [comment]
> I've done some testing in Vagrant. Looks good to me to release

Cool, here we go !

**Pull request merged**
