### PR TITLE
chore(ci): add closed references notificier workflow

### PR DESCRIPTION
**Pull request by jooola**
This workflow will check for issue links in the code
that has been closed upstream and can be dealt with.

### CODE REVIEW

**Comment by paddatrapper** [comment]
Can you elaborate a bit more on what this does?

**Comment by jooola** [comment]
It scans our codebase for issue links, and checks if the issue is closed upstream. If it is closed, the notifier will open a new issue that the link in the code should be removed or dealt with.

**Comment by paddatrapper** [comment]
Looks good. Only comment is that this isn't a chore(ci), it should just be ci: as if semantic release was run, this should not cause a point release (which chore would). For more examples of type and scope see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format

**Comment by jooola** [comment]
@paddatrapper Aah good point, not totally familiar with conventional commits yet !

**Pull request merged**
