### PR TITLE
add clock icon for autoloading playlists in calendar, remove empty show alert

### PR DESCRIPTION
**Pull request by frecuencialibre**
unfortunately this also includes a bunch of formatting cleanup done automatically by my text editor, and now i don't have time to fix that.

### CODE REVIEW

**Comment by frecuencialibre** [comment]
hold up. not ready for merge. this would undo recent changes to airtime_mvc/public/css/styles.css

**Comment by Robbt** [comment]
The formatting stuff shouldn't be an issue but I noticed it removed  .show_autoplaylist_help_icon { from line 207 of style.css - that doesn't seem intentional but a artifact of this being done before we did the other PR. So it probably should be changed.

**Comment by Robbt** [comment]
Cool, those icons are so small but that's not really the problem of this. It seems to work but I'm still seeing the red ! for shows with autoloading playlists.

**Comment by frecuencialibre** [comment]
could your browser be caching the js file that adds those? i typically refresh with the "disable cache" checkbox checked in the Network tab of firefox or chrome devtools.

**Comment by Robbt** [comment]
yeah it was a caching issue. I just did a shift refresh and it worked. Going to merge this now as I think it is good.

**Pull request merged**
