### PR TITLE
Cors in setup

### LINKED ISSUE #917: Set CORS URLs in web installer
The CORS Urls setting is required when running LT behind a proxy (Containerisation is a common use case). The only documentation currently is [here](http://libretime.org/manual/general/), but it only contains one line:

> The Allowed CORS URLs is intended to deal with situations where you want a remote site with a different domain to access the API.

This should be elaborated on and highlight proxy use-cases. Maybe a "Common Setups" section in the Getting Started section, or Tutorials.

### PR DESCRIPTION
**Pull request by Robbt**
This fixes #917 
Needs tested on a completely new install but appears to be working.
Didn't pull existing CORS values from the database if for some reason the people see the install screen again it won't overwrite them. Tried to add that to text. Hopefully most people will ignore it unless they know otherwise that they need to input CORS values due to additional documentation etc that we write about setup for Docker/reverse proxy.

### CODE REVIEW

**Comment by paddatrapper** [comment]
Works in a new install with proxy in front. The only thing I would suggest is including instruction to place each URL on a new line

**Comment by Robbt** [comment]
Ok done. Wasn't sure if you needed to include the http:// prefix as well as https://URL, so if this isn't clear or we don't need http in there and just want the host name we can clarify that as well.

**Comment by paddatrapper** [comment]
I'll text just using the hostname without protocol and see what happens

**Comment by paddatrapper** [comment]
Just tested - you need to include the protocols

**Pull request merged**
