### PR TITLE
feat: use dedicated 'libretime' user with nginx + php-fpm

### LINKED ISSUE #1186: Nginx suport
I would like you to give it support for nginx

### LINKED ISSUE #1637: Dedicated user that run libretime
We should consider adding a dedicated user to run the multiple LibreTime services.

For now we use `www-data` to run all the services. I think `www-data` is a generic user that might have already too much permission and might be used by other programs.

`www-data` will still  be used to serve files with the web server and handle uploads, but I would go towards a php-fpm solution, with the php process running as `libretime` and `www-data` simply having read only permission where it is needed.

We also have a dedicated `celery` user, but I think we should remove this celery user and use this new `libretime` user.

Regarding the backend services such as playout or analyzer, they definitely don' require the `www-data` user.

Depending on web server stack structure, we should have:
```bash
# Running user: libretime
/etc/systemd/system/libretime-analyzer.service

# Running user: libretime
# what about the uwgsi package user?
/etc/systemd/system/libretime-api.service

# Running user: libretime
# what about the celery package user?
/etc/systemd/system/libretime-celery.service

# Running user: libretime
/etc/systemd/system/libretime-liquidsoap.service

# Running user: libretime
/etc/systemd/system/libretime-playout.service

# Owner: libretime
# once liquidsoap does not write here anymore, we could change the permission to root
/etc/airtime

# Owner: libretime
# add www-data to the libretime group, for read only permission
/etc/airtime/airtime.conf

# Owner: libretime
/var/log/libretime

# Owner: libretime
/var/lib/libretime

# Owner: libretime
# how does the webserver write in here ?
/srv/airtime
```

### LINKED ISSUE #1719: Replace uwsgi with a ASGI replacement
Moving towards the modern ASGI protocol, to support async and websockets.

https://asgi.readthedocs.io/en/latest/introduction.html#what-s-wrong-with-wsgi

I propose to use uvicorn + gunicorn https://docs.djangoproject.com/en/4.0/howto/deployment/asgi/uvicorn/

### PR DESCRIPTION
**Pull request by jooola**
- Fixes #1186
- Fixes #1637
- Fixes #1719

### CODE REVIEW

**Comment by jooola** [comment]
@paddatrapper I am all for using unix socket between nginx and php-fpm or gunicorn, but I wanted to have your input if you see anything bad with it ?

**Comment by paddatrapper** [comment]
It will work for general use, but it will need to change for Docker - ideally php-fpm would be in a different container, so connecting via http would make more sense there

**Comment by jooola** [comment]
> It will work for general use, but it will need to change for Docker - ideally php-fpm would be in a different container, so connecting via http would make more sense there.

I had this in mind, so I thought we might want to use tcp sockets, but I feel tweaking the listen socket isn't a bit problem as we will have to edit it anyway to specify the containers names.

Unix socket it is ! (This is going faster than I expected to upstream those differences https://github.com/libretime/ansible-role-libretime/issues/15)

**Comment by jooola** [comment]
Tested fresh install and upgrade from main to this branch, it is working as expected if we properly follow the upgrade procedure.

**Comment by jooola** [comment]
Add the uvicorn asgi server. Tested again on bullseye !

**Pull request merged**
