### PR TITLE
Autoplaylist calendar fix

### PR DESCRIPTION
**Pull request by xabispacebiker**
This small fix displays a new icon in the autoplaylist schedules, also removes the "show empty" red icon to avoid confusion:

autoplaylist_calendar_fix

### CODE REVIEW

**Comment by Robbt** [comment]
So this replaces the green A with the 3 horizontal lines and removes the red exclamation mark from shows that have an auto playlist ?

This makes sense to me.

**Comment by frecuencialibre** [comment]
i got [up and running](http://github.com/frecuencialibre/libretime-docker-dev), tested this and can confirm it works as described. 

I agree that we should merge this now, but also see a few ways this PR could be improved:
- I associate the "hamburger icon" with a menu. The A stood for automatic, but that isn't translatable, and is [in flux](https://github.com/LibreTime/libretime/issues/560#issuecomment-438293763). I don't have any brilliant ideas, but perhaps a clock?
- The exclamation point is removed if a playlist is assigned. It has no relationship to whether the show is actually full. Ideally we would hook into the same system that is used for conventionally scheduled content, but I'd guess we have other pressing issues to fix first. 

Awesome! thanks @xabispacebiker !

**Comment by Robbt** [comment]
So I agree that a clock would probably be better I found the [eva collection](https://akveo.github.io/eva-icons/#/) of open-source icons has this clock [icon](https://akveo.github.io/eva-icons/outline/png/128/clock-outline.png) which looks like it would work. Perhaps we could use that instead of the hamburger menu.

Also I think that if we are going to remove the RED ! then we should replace it with some kind of indicator so that people can see if a show was scheduled or not. It is also useful to have the orange partial scheduled icon visible, especially to easily gauge whether a autoloading playlist failed to fill the show for some reason. Perhaps we could change the icon though or even color-code the clock icon. Just thinking about it. I don't want to remove it all together but it could definitely make sense to change it.

**Comment by frecuencialibre** [comment]
i like the clock you found. i think it's definitely an improvement over the menu icon. the red exclamation point never disappearing despite having scheduled an autoloading playlist is confusing to people at my station. 

color coding the icon is an interesting thought, and easily done with css classes if we add it as an inline svg, but i'm not sure people would understand it. the orange and red exclamation point icons are already present in the UI, and already have established meanings.

how complicated would it be to either 1. check whether or not the show is actually full using the system that is used for conventionally scheduled content, or 2. show a css class conditionally depending on whether or not the repeat checkbox is checked?

my vote: 
1. to replace the menu icon with the clock, keeping current conditional display logic. 
2. if either of the two options i ask about above are feasible, then use one to conditionally add the yellow exclamation point. 

@xabispacebiker thoughts?

**Comment by frecuencialibre** [comment]
after concluding with @Robbt that there is no good way to gauge whether an autoloading playlist will fill a show, i went ahead and did the icon change without adding any extra logic. it's this same PR with a few very small fixes to @xabispacebiker 's work: https://github.com/LibreTime/libretime/pull/615

**Pull request closed without merging**
