### PR TITLE
WIP: Pull the new front page website from ned-kelly

### PR DESCRIPTION
**Pull request by Robbt**
This is just pulling the commit from @hairmare that preserves the commits that @ned-kelly did.

### CODE REVIEW

**Comment by frecuencialibre** [comment]
is this ready for merge? or do we need to [test travis locally](https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally)?

**Comment by hairmare** [comment]
I see the following points that we should look into:
* [ ] remove node_modules from merge
* [ ] ensure that we always use a fresh build (and thus don't need to commit the build results) on each deploy
* [ ] clarify what's up with `site/LICENSE` (which is MIT contrary to the rest of the repo and and should probably be CC-* for the content and possibly AGPL for the technical parts of the site)

**Comment by Robbt** [comment]
So as an alternative to merging this PR and pushing the site into the core repo we could also just have @ned-kelly transfer it (when we open up that permission and set the current site to be docs.libretime.org.

This would appear to resolve some of these above issues at least with the multiple licenses, node_modules and if we keep node then we could just build it.

I have never setup a github site or travis CI so I don't know how it works exactly but if just transferring the existing repo would be easier we could still go that route.

**Comment by hairmare** [comment]
The thing about the node_modules is that this PR still kills my browser when I look at the changes in the we view. I tried to fix this already on the changes already in the PR but will need to rebase them a few times until the .gitignore matches up with the actual contents of the merge. Right now this would make the libretime source grow considerably by pulling the full build environment that made it into the tarball.

The licencing won't be much of an issue, it just needs some proper attribution in like the LICENSE_3RD_PARTY file. We would be sublicensing the MIT code under our license which isn't much of an issue for MIT afaik (ianal, ymmv, etc).

Relicensing the actual contents to a real content license (like any CC-* one) is something we can only do with Ned's consent, but it would be smart. The current situation with the actual docs being under a software rather than a documentation licence isn't perfect already so it would be nice not to add to that.

What I forgot to mention is that the travis parts are already well tested and I don't really see an issue why they wouldn't work. It's really more that I don't want everyone's working copy to explode just because we merge this in it's vendored form.

**Comment by hairmare** [comment]
@frecuencialibre I'll try to take care of the points in my comment over the weeked. If you would like to work on the site you can do so at ned-kelly/libretime-website. I'm watching the repo and I also have write access to it so I can review/merge stuff there as well. If we do end up merging anything there I'll just rebase the contents of this PR. If you want to base your work on my stuff already in this PR you can create a PR against the `radiorabe:chore/integrate-site` branch this PR is based off but I would probably recommend to PR on the original repo at the moment.
Sorry about not getting on this earlier, it's simply that I usually try to look at actual technical stuff first and marketing stuff like this is a bit less pressing on my prioritized todo list.

**Comment by frecuencialibre** [comment]
Thanks Lucas! 

>  I usually try to look at actual technical stuff first and marketing stuff like this is a bit less pressing on my prioritized todo list.

Perfect. Hopefully we can be proactive to reduce dependence on you for this kind of thing.

**Comment by ned-kelly** [comment]
Hi guys - just getting back on my feet after being away for the last 30 days - Glad this is making some progress, i've got a bucketload of things to catch-up on, sing out if there's any issues in with this that directly requires my involvement - It looks like you've got it all under control for now!

**Comment by hairmare** [comment]
Hey @ned-kelly Welcome back!

If you could publicly to consent us re-licensing sites content (ie. the copy you wrote) to [CC-bs-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0/) (an actual content licence and not a code license) that would help me check off another box https://github.com/LibreTime/libretime/pull/590#issuecomment-437980199.

We also invited you to the Maintainers team on GitHub so you can maintain this after the merge. Please check the [C4](https://rfc.zeromq.org/spec:42/C4/) for more details on a Maintainers responsibilities. You can accept or decline the invite on the main orga page: https://github.com/LibreTime

Cheers

**Comment by ned-kelly** [comment]
Lucas,

Not a problem - I've joined the org and happy to proceed re the change of
license - At the end of the day it's just static HTML so no big deal what
license it falls under.

Let me know if there's anything else.

Cheers,

*-- David Nedved*

au: +61 499 150 625
ph: +63 949 594 0636

david@nedved.com.au

*Connect with me on:*
Twitter  <http://twitter.com/davidnedvedau>| LinkedIn
<https://www.linkedin.com/in/davidnedved/>
*Confidentiality Note: *This email may contain confidential and/or private
information. If you received this email in error please delete and notify
the sender.

**Comment by Robbt** [comment]
Is this ready to go or do we need to do more work before we can push it live ?

**Comment by hairmare** [comment]
It's almost there, just some cleanup and small docs fixes as per https://github.com/LibreTime/libretime/pull/590#issuecomment-437980199

**Comment by gusaus** [comment]
Are we waiting for a particular person to resolve the remaining issues in https://github.com/LibreTime/libretime/pull/590#issuecomment-437980199 or can others help?

**Comment by Robbt** [comment]
I think we should consider this change as something that we do to "launch" the beta of LibreTime and we should prioritize fixing the other issues in #544 but do whatever ground work is needed to make this happen.

**Comment by Robbt** [comment]
Since we haven't heard from @ned-kelly much recently, I don't think we should hinge whether we declare our software beta based upon having a nice launch page, or at least not this specific one. If Ned shows back up and wants to work on this we can move forward with it but I'm taking away the release blocker status.

**Comment by zklosko** [comment]
In a way, this was "fixed" by #1030. Is there something we can pull from this PR into our new website?

**Comment by Robbt** [comment]
Yeah I'm going to close this as we have a new website and work is happening on a even more aesthetically pleasing one.

**Pull request closed without merging**
