### PR TITLE
docs: create 3.0.0-alpha.12 versionned documentation

### PR DESCRIPTION
**Pull request by jooola**

### CODE REVIEW

**Comment by paddatrapper** [comment]
Is there no way of doing this based on git history, i.e. a git commit hash reference? Duplicating all the docs every release doesn't seem sustainable

**Comment by jooola** [comment]
This is how docusaurus handle versioned documentation, I agree it's not really clean, but I guess that they thought this through when building the software. If we really don't want to handle it this way, we will have to rely on a branch and some extra workflows. I'll have a look at a possible different solution.

**Comment by paddatrapper** [comment]
Ok. Then I think cleaning this up is something we can kick down the road

**Comment by jooola** [comment]
What could happen is, we have the PR's review website on libretime.github.io/pr-{pr-number}, we could have the latest versioned docs on libretime.org and the unreleased docs on libretime.github.io/next/ ?

**Comment by paddatrapper** [comment]
A lot of people run main at the moment, so I think let's have the two on the website for now

**Pull request merged**
