### PR TITLE
feat: create bulk-import tool

### PR DESCRIPTION
**Pull request by jooola**
A small tool to build imports an entire directory of files. It can be used as replacement for the "Watched folders" features.

### CODE REVIEW

**Comment by zklosko** [comment]
How is the watched path set?

**Comment by jooola** [comment]
The script does not watch a folder, it simply does a bulk import. Run `./tools/bulk_import.py --help` to get the usage manual.

**Comment by paddatrapper** [comment]
If we intend to point people to this, it should probably be documented in the admin docs. Also is this using v1 or v2 of the API?

**Comment by jooola** [comment]
It upload the files to the legacy api, as the api v2 does not have a upload endpoint, right ? At least it doesn't trigger the entire import pipeline with the analyzer.

**Comment by zklosko** [comment]
Can we add this to #1620? I think once this is in we can finally release our 3.0 beta.

**Comment by paddatrapper** [comment]
> It upload the files to the legacy api, as the api v2 does not have a upload endpoint, right ?

Not currently by the looks of things. Needs implementing in the FileViewSet. Once we drop the PHP API, we can update the model to use a FileField and abstract most of it to Django to handle

**Comment by paddatrapper** [comment]
LGTM. Needs documentation and then I'm happy to merge

**Comment by jooola** [comment]
I would like to let it sit here for a bit, I have some improvements/fixes in mind and I would prefer no shipping this in alpha.11.

**Comment by jooola** [comment]
I'll reimplement this tool into a django management command.

**Pull request closed without merging**
