### PR TITLE
Hideable Scheduled Shows tab

### PR DESCRIPTION
**Pull request by hairmare**
Makes the first tab remoeable and the tracks page be full width after removing the last tab. You can press the "Dashboard" link to open it back up again.

### CODE REVIEW

**Comment by Robbt** [comment]
It works but I think that the UI could a little bit improved.  From what I saw there was only 3 dots to the right of scheduled shows. I think that it might be better to have an arrow or some other indicator. I also noticed that the area I could click on was somewhat limited.

**Comment by hairmare** [comment]
It should be an X on the tab like the other tabs have. The three dots happens when the text doesn't fit. Maybe I missed some CSS. I'll have a closer look at it.

**Comment by hairmare** [comment]
This is what it should like:

screen shot 2017-03-23 at 11 24 45

If the text is clipped a bit and showing dots your browser might still have a cached version of the css changed by this. I had to do a lot of <kbd>Cmd-Shift-R</kbd> reloading to hack on the css.

**Comment by Robbt** [comment]
Ok, in the dashboard.css I needed to change the max-width to 160px vs. 140px to get it to show.
I figure this is probably something with Firefox vs. Chrome.

I can't do the push right now but here is the section that needs to change from my testing.

.tab-name {
    float: left;
    max-width: 160px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}

**Comment by hairmare** [comment]
I'll give both a try and apply it.

**Comment by hairmare** [comment]
I wasn't able to reproduce it, maybe my Firefox Aurora install is too hipster for it. I did the change anyway since a larger `max-width` shouldn't hurt anyway.

**Pull request merged**
