### PR TITLE
Update composer.lock versions

### LINKED ISSUE #774: composer.lock file outdated
as of now we are version controlling the `composer.lock` file but problems have arisen. I'm pasting here relevant parts of a side conversation that happened in #683 , but which was beyond the scope of that PR:

i'm not qualified to give an opinion regarding whether or not `composer.lock` should be version controlled, but my reading of the error i hit upon deleting it and running `composer install` is that the .lock file was strictly specifying files that the more flexible (eg. ^, ~ syntax) json file's dynamic query can no longer find in the celery-php repo. right? the error again:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package massivescale/celery-php 2.0.*@dev exists as massivescale/celery-php[2.1.1, 2.1.2, dev-celery4, dev-celery4_pr66, dev-drewpctest, dev-master, 3.0.x-dev, dev-revert-117-persis] but these are rejected by your constraint.
```
just swapping `"massivescale/celery-php": "2.0.*@dev"` for `"massivescale/celery-php": "dev-master"` gets past the error, but no idea whether that messes up things for celery.

### php
Following an error-free install process, visiting `http://localhost:8080/` still throws our good 'ol firend `compact(): Undefined variable: extras#0 ...`.

1. Simply deleting the vendor file and running `composer install` does not resolve the error, and also shows this message: 
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```

2. `composer update` seems to have worked wonders, although a bunch of things changed, output below. Not only does the zend-view error resolve, but i'm also able to save the general settings page confirming that @Robbt 's work in #737 . I'm able to upload tracks, add them to shows, and hear them output by liquidsoap. Next up will be to systematically check functions.

```
vagrant@debian-buster:/vagrant$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 15 updates, 0 removals
  - Removing zf1s/zend-view (1.12.20)
  - Installing zf1s/zend-view (dev-master 89acaef): Cloning 89acaef8c2 from cache
  - Updating php-amqplib/php-amqplib (v2.6.3 => v2.8.1): Downloading (100%)
  - Updating symfony/event-dispatcher (v2.7.4 => v2.8.49): Downloading (100%)
  - Updating predis/predis (v1.0.3 => v1.1.1): Downloading (100%)
  - Updating sebastian/recursion-context (1.0.2 => 1.0.5): Downloading (100%)
  - Updating doctrine/instantiator (1.0.5 => 1.1.0): Downloading (100%)
  - Updating sebastian/diff (1.4.1 => 1.4.3): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.10.0): Downloading (100%)
  - Installing webmozart/assert (1.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Updating phpdocumentor/reflection-docblock (2.0.4 => 4.3.0): Downloading (100%)
  - Updating phpspec/prophecy (v1.6.2 => 1.8.0): Downloading (100%)
  - Updating phpunit/php-file-iterator (1.4.2 => 1.4.5): Downloading (100%)
  - Updating symfony/yaml (v2.8.17 => v3.4.22): Downloading (100%)
  - Updating phing/phing (2.12.0 => 2.16.1): Downloading (100%)
  - Updating phpunit/php-token-stream (1.4.10 => 1.4.12): Downloading (100%)
  - Updating simplepie/simplepie dev-master (eb6dd2d => 0e8fe72):  Checking out 0e8fe72132
  - Updating zf1s/zend-validate dev-master (065da57 => 424607a):  Checking out 424607a115
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package raven/raven is abandoned, you should avoid using it. Use sentry/sentry instead.
Writing lock file
Generating autoload files
```

**LibreTime version:**
current head

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes #774 

I want to run the CI pipeline against the change to see what breaks

### CODE REVIEW

**Comment by paddatrapper** [comment]
So the errors occur because of PHP 5.4 and 5.6:

```
  - symfony/yaml v3.4.23 requires php ^5.5.9|>=7.0.8 -> your PHP version (5.4.45) does not satisfy that requirement.
    - phpdocumentor/reflection-common 1.0.1 requires php >=5.5 -> your PHP version (5.4.45) does not satisfy that requirement.
    - Installation request for phpdocumentor/reflection-docblock 4.3.0 -> satisfiable by phpdocumentor/reflection-docblock[4.3.0].
    - phpdocumentor/reflection-docblock 4.3.0 requires php ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - phpdocumentor/type-resolver 0.4.0 requires php ^5.5 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - symfony/yaml v3.4.23 requires php ^5.5.9|>=7.0.8 -> your PHP version (5.4.45) does not satisfy that requirement.
```

**Comment by paddatrapper** [comment]
This is now ready to merge

**Comment by frecuencialibre** [comment]
awesome work! so i'm guessing the `composer.lock` change is the result of running the commands you posted [here](https://github.com/LibreTime/libretime/issues/774#issuecomment-477567535)?

the commit i added is my attempt to also pull in @Robbt 's fix for the other 7.3 bug that happened upon hitting the save button at settings > general. look ok?

**Comment by paddatrapper** [comment]
Yup. Looks good

**Comment by paddatrapper** [comment]
I have also added the method to the [wiki](https://github.com/LibreTime/libretime/wiki/PHP-Composer-Update-Procedure)

**Pull request merged**
