### PR TITLE
fix: force_ssl logic in pypofile

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes: #1172

### CODE REVIEW

**Review by fulltimecoffeegrinder — COMMENTED** [review]
OnAir-Light is fixed now
But playout only silence. No Audio output to icecast

**Comment by paddatrapper** [comment]
@fulltimecoffeegrinder should now work for icecast audio too

**Comment by fulltimecoffeegrinder** [comment]
Hi @paddatrapper . Unfortunately it doesn't work for me.
The 'output going off' problem seems to be solved - ON AIR Light stays on - but icecast is not playing audio.
It displays the "LibreTime - offline" message.
Tried on two different Ubuntu 18.04 machines and an independent, complete new installation. (Ubuntu 18.04 + Libretime on VM). Cluelessly greetings

**Comment by paddatrapper** [comment]
Please post a link to your /var/log/airtime/pypo/pypo.log

**Comment by paddatrapper** [comment]
As this is urgent and seems to fix the issue (see comments in #1172), I am going to merge this

**Comment by fulltimecoffeegrinder** [comment]
Hi @paddatrapper !
The Problem is solved perfectly! I have to revise my last post.
The fix works for me. Thanks for your efforts.

**Comment by radiobijoux** [comment]
I applied this fix, rebooted and scheduled an hour playlist.  After 3 songs, the broadcast went silent.  At that point, as a new song cues and begins playing, the OnAir light comes on for a few seconds, then goes back off, but no sound ever plays.  This is on a fresh install from git, on Ubuntu 18.04 with all of the latest updates applied, and no other edits made to the LibreTime system or the O/S.  Just a generic plain vanilla install.

**Pull request merged**
