### PR TITLE
Fix nonmp3 podcast download

### LINKED ISSUE #271: Problem: certain podcasts fail to download files with "can't sync to an MPEG frame" error
Hello everyone,

This is a bit of a feature request and a question at the same time.  I run an online podcast network.  We do live streaming using an icecast server, but are looking to add pre-recorded shows as well.  These shows are all podcasts and release shows on a daily and/or weekly basis.  I have created a java program that will automatically download the latest episode of each show and put in a specific folder.  I have seen an issue or two dealing with podcasts, so maybe I'm missing a feature that already exists in LibreTime, if so, apologies.

But, I would like to create a schedule in LibreTime and just replace the files every day with the newest version.  Based on my limited understanding (I'm new to LibreTime/Airtime) each new file gets it's own database entry, so I'm not sure I can just replace files.  When I try to do a smart list, it seems to select the files when I add them to the show and never get updated again.

Does anyone have an idea of how I might set up this automated solution?  

Thanks,
Adam

### LINKED ISSUE #519: Downloaded m4a podcast's failing to import with "can't sync to an MPEG frame" error
As the subject suggests, am having issues with podcasts that are in M4A format importing to Libretime.

Summary:

- Files are being created in /tmp when adding podcast (that's m4a format) and being downloaded
- File appears to be fully downloaded ok, but then failing to import to library.
- Files in /tmp/ are owned by "celery:celery"
- Example Podcast: http://podcast.djhardwell.com/podcast.xml
- I'm seeing the following in one of the celery worker logs:

```
[2018-09-18 11:41:03,657: INFO/Worker-1] podcast-download[php_5ba0e4352a6c74.76761676]: Error during file download: can't sync to an MPEG frame
[2018-09-18 11:41:03,718: INFO/MainProcess] Task podcast-download[php_5ba0e4352a6c74.76761676] succeeded in 26.512139958s: '{"status": 0, "episodeid": 223, "error": "can\'t sync to an MPEG frame"}'
```

I've read that the python `mutagen` package required by `airtime_analyzer-0.1-py2.7.egg` could be a cause (it's currently mutagen==1.31) - I've tried upgrading it to the latest (mutagen 1.41.1) and it's no help unfortunately.

System details:
- Running Ubuntu Xenial
- silan 0.3.2-2build3
- Python 2.7.12
- Celery args are: `--time-limit=1200 --concurrency=4 --config=celeryconfig -l INFO`

Would welcome suggestions on where to look / potential fixes - Anyone know if merging in https://github.com/LibreTime/libretime/pull/464 will help here?

Regular MP3's are fine - Could we perhaps just find a way to pipe any other formats through something like `ffmpeg` before having the files imported for now which should fix this (not sure where to look, or I'd already be trying this now)

I believe what may be cause of the problem is that the podcast's "album art" actually changes multiple times throughout the mix (as the track names change, the album art updates to reflect the track names) - This is pretty common with EDM podcasts from big name artists/shows (ASOT, Tiesto etc) when you look at the podcasts they have on iTunes.

### PR DESCRIPTION
**Pull request by Robbt**
This fixes #519 by taking away the mp3 specific code and replacing it with mutagen library as a whole which supports most filetypes except for WAV, and I don't think there are very many WAV based podcasts.
I tested it with the m4a based podcast referenced in #519 and was able to download without an issue whereas before it was failing.

Also fixes #271

### CODE REVIEW

**Comment by Robbt** [comment]
ugh it looks like I forgot to checkout of the remove mutagen 1.31 version PR before I did this code change. So that is getting pulled in. It shouldn't be an issue if we merge #619 before this one.

**Comment by hairmare** [comment]
I've been holding off on merging this since I'd like to do some testing. At a quick glance and also considering the mutagen docs it looks more than fine.

**Comment by frecuencialibre** [comment]
did some testing on this one, and unfortunately the jury is still out. 

first, without a re-install, i simply checked out this PR branch, and then tested two podcasts, the hardwell one above, and an [mp3 one](https://archive.org/services/collection-rss.php?query=uploader:noticiasdeabajoml@gmail.com) we use. ... and manual import of the most recent episodes (following the steps in the wiki) of both podcasts worked!

great, but then i tried a fresh install. the mp3 podcast still worked, but the m4a one failed with the same `can't sync to an MPEG frame` error in zendphp.log. more info:
- i noticed that i [apparently was still running mutagen 1.31](https://github.com/LibreTime/libretime/pull/619#issuecomment-448720417).
- python_apps/airtime_analyzer/setup.py does in my tested codebase does show the removal of the mutagen version restriction
- manual import as an individual track through the web UI of the [first episode of the m4a podcast](http://test.podcast.djhardwell.com/HOA250.m4a) worked. 

any suggestions on how to further troubleshoot? manually update mutagen?

**Comment by Robbt** [comment]
I noticed it indeed was at 1.31 on my ubuntu-xenial, perhaps this is because this version of mutagen is provided by the distro by default and so it uses that vs. downloading the newest version from pip.

I decided to test pushing the version manually up to 1.41.1 or above in the requirements and it is still failing now for me as well, which is odd considering I had it working previously. 

I'm very perplexed and I'm going to look at the code to see what could have happened.

**Comment by Robbt** [comment]
Ok, I think I have figured this out, for some reason the line `logger.debug('podcast_download loaded {0}'.format(audiofile.name))` was causing the error for me but when I removed that everything worked even with mutagen 1.31 - I am suggesting we keep the mutagen 1.41.1 though because 1.31.0 had some other errors and is still coming by default. I'm not sure why as I can't find any places referencing it. It is kind of a messy commit to modify the airtime_analyzer code in fixing this but since I already had that commit log bundled I don't think it will cause too much confusion to anyone browsing it in the future.

@frecuencialibre can you see if this new version works for you with the m4a podcast ?

**Comment by hairmare** [comment]
On a fresh debian-stretch vagrant machine the pypo install seems to install mutagen==1.36 which then gets updated to mutagen==1.41.1 as soon as the installer reaches the airtime_analyzer dir. I'm not sure why it's doing this since pypo doesn't actually specify a mutagen version (I would expect mutagen to install in a latest version without any requirements but I don't seem to understand pip reqs properly 😛).

I just imported a head of tracks and some podcasts to my test instance and will do some listening to be sure everything still looks sane before I merge this. I think we can address what's happening with mutagen installed by pypo vs analyzer in a later PR if needed.

BTW the only distro that already has  mutagen 1.41.x is Fedora 29 which is at 1.41.0. Debian and Ubuntu both have 1.40.x in their latest testing repos ([source](https://pkgs.org/download/mutagen)).

**Comment by hairmare** [comment]
This also fixes non mp3 formats for non podcast cases... ie. if you can upload it and it has metadata that are reachable by mutagen then those will get considered.

**Pull request merged**
