### PR TITLE
make podcast creation UI conform to standard content creation UI 

### LINKED ISSUE #647: Feature request: make podcast creation UI conform to standard content creation UI
**Problem:** 
Currently creating a podcast involves a modal window (the only one that exists in libretime), which upon submit shows you a list of episodes in the left pane. This modal, and also the "back" and "forward" chevron buttons in the podcast left pane all contrast sharply with Airtime's established content creation workflow, as seen with playlists, webstreams, and smartblocks, which shows lists of editable content in the left panel, and tabs of forms in the right panel. I've watched people be confused by this inconsistent/broken visual language.

**Proposed solution:**
Following on from work done in #637, I plan to research feasibility of adapting the podcast Angular 1 app to create something along these lines:

screenshot from 2018-12-14 06-21-05

any thoughts or help very much welcome!

### PR DESCRIPTION
**Pull request by frecuencialibre**
Closes #647

### CODE REVIEW

**Comment by paddatrapper** [comment]
Thanks for this! Are you able to update the docs around playlists to reflect these changes?

**Comment by frecuencialibre** [comment]
unfortunately no docs have yet been written for podcasts: http://libretime.org/search.html?q=podcast

all that exists is the [wiki](https://github.com/LibreTime/libretime/wiki/Automatic-Playlists,-Smartblocks-and-Podcasts) @Robbt wrote. my personal plan has been to focus on first fixing UI, and then docs, since videos and screenshots showing outdated UI are confusing.

**Comment by paddatrapper** [comment]
Ah I see. hmm... I may have time to do some work on the docs over the next two weeks, but not sure

**Comment by frecuencialibre** [comment]
is this one workign for you?

**Comment by frecuencialibre** [comment]
https://github.com/LibreTime/libretime/issues/633 will also bring some slight change to podcast UI and so should land before work on documentation. we're thinking the override will be of the artist rather than the album.

**Comment by paddatrapper** [comment]
I'm busy testing it at the moment (waiting for vagrant to stand up)

**Comment by paddatrapper** [comment]
> is this one workign for you?

I'm busy testing it - waiting for vagrant to finish standing up

**Comment by paddatrapper** [comment]
It seems I keep getting a vagrant build error (on any machine I test master or any other branch):

```
    ubuntu-xenial:     Failed to download zendframework/zendframework1 from dist: Could not delete /vagrant/vendor/zendframework/zendframework1/.nfs0000000000980dde00000002: 
    ubuntu-xenial:     Now trying to download from source
    ubuntu-xenial:   - Installing zendframework/zendframework1 (1.12.20): 
    ubuntu-xenial:                                                                                                
    ubuntu-xenial:   [RuntimeException]                                                                           
    ubuntu-xenial:   Could not delete /vagrant/vendor/zendframework/zendframework1/.nfs0000000000980dde00000002:  
    ubuntu-xenial:                                                                                                
    ubuntu-xenial: 
    ubuntu-xenial: install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Any ideas?

**Comment by frecuencialibre** [comment]
yeah i [got that error too](https://github.com/LibreTime/libretime/pull/670#issuecomment-452922236) while testing the zf1s PR... i'm pretty sure it's unrelated to this one since the only changes here are to two javascript files and a phtml template. interesting that you're getting this same error when standing up this pr. i had assumed it was related to the zf1s changes.

i'm not sure where to start troubleshooting this one... i'm pretty new to vagrant, and have only a basic knowledge of php.

**Comment by Robbt** [comment]
> #633 will also bring some slight change to podcast UI and so should land before work on documentation. we're thinking the override will be of the artist rather than the album.

My thought is that it would override both album & artist but we haven't decided upon anything fully.

**Comment by frecuencialibre** [comment]
oops you're right @Robbt sorry for replying too quick

**Comment by frecuencialibre** [comment]
looks like i hadn't committed a small template change. testing this on a different box it was breaking completely, but should now be fine

**Comment by Robbt** [comment]
Looks good. I found the inclusion of the search bar to be interesting.
My only potential complaint was that when searching the podcast if there are no matching tracks the message displayed is incorrect. 
"This podcast doesn't have any episodes!
Make sure the RSS feed contains audio items (with enclosure tags)."

It should have a different message if there are episodes but nothing matches the search result, but I don't know how much of a pain that would be to implement and it isn't a big deal. I don't know how useful the search will be though in general because the podcast table doesn't link directly to the tracks.

Anyways, I think this is ready to merge but wanted to give you a chance to decide whether we want to fix the message on the search before we push it.

**Comment by frecuencialibre** [comment]
good catch! that "This podcast doesn't have any episodes!" message seems to be more of a check that should be shown as soon as you've submitted the modal with a new podcast. Unfortunately logic to conditionally display different messages would have to be built separately, since that message is just an "emptyPlaceholder" argument provided to the dataTable creation function. Hence I'd say we add this UI bug to our list of podcast tasks to be handled in a separate PR.

yeah the actions that can be taken from that episodes table are to view the episode description (globe icon), import, and delete them. so the use case here is if you want to manually download episodes. did you test those?

**Comment by Robbt** [comment]
Yeah manual importing worked fine. The UI is still kind of clunky ie no way to access the track directly from the podcast interface once it is downloaded and/or fix or retry broken downloads but that is because of the original design and this change is an improvement in general in my opinion.

**Comment by frecuencialibre** [comment]
> clunky

yup. but helpful in order to get clearer on use cases to be accounted for in next gen

**Pull request merged**
