### PR TITLE
Enhanced weekly widget [WIP]

### PR DESCRIPTION
**Pull request by JohnnyC1951**
Adds Show Logo, Description and Show URL link and adds abbreviated timezone to show times (avoids confusion across time-zones).
screenshot from 2018-02-11 01-36-37
screenshot from 2018-02-11 01-35-38

### CODE REVIEW

**Comment by JohnnyC1951** [comment]
I think I doubled up by mistake :( sorry.

**Comment by korotkov13** [comment]
It's cool feature. I waited so long for it. 
I tried it, and found one inconvenience. If I upload a picture(300x300 or other size) it shows full sized in widget. It would be cool if all the pics would be resized automatically to page resolution.
I don't know how to make it. It is just users feedback. 
Thanks again for your work.

**Comment by JohnnyC1951** [comment]
A revised version attached & footnotes.
I think the problem you had with the link was that you had no url defined in the show url.

1.  It does not show or have any hyperlinks if the show url field is empty.
2. The width of the show logo is now scaled to 80px wide.
3. Other changes: reduced panel padding by 20px on each side
4. Be aware that huge numbers of large logo images will slow down the page load.

I would have done another pull request, but I am not authorized to do that (it said when I tried).
[weekly-program.phtml.zip](https://github.com/LibreTime/libretime/files/1714676/weekly-program.phtml.zip)

**Comment by korotkov13** [comment]
Thanks!
One more thing that I did not understand. how to change the time from 12 to 24 hours in format?
It's shows  only in 12hours format

**Comment by JohnnyC1951** [comment]
Change:

"show_start_hour": start_date.toLocaleTimeString([], { hour: 'numeric', minute : 'numeric' }),
"show_end_hour": end_date.toLocaleTimeString([], { hour: 'numeric', minute : 'numeric' }),

To: (or other locale that uses the 24hr clock)

 "show_start_hour": start_date.toLocaleTimeString(['en-GB'], { hour: 'numeric', minute : 'numeric' }),
"show_end_hour": end_date.toLocaleTimeString(['en-GB'], { hour: 'numeric', minute : 'numeric' }),

**Comment by JohnnyC1951** [comment]
All new version coming very soon. Please do not merge this.

**Comment by Robbt** [comment]
Ok, the convention is to add [WIP] to the title this will prevent merges. I'll do that for you. Edit the title and remove the [WIP] when it's been updated. Thanks.

**Comment by JohnnyC1951** [comment]
Thanks Robbt. I had no idea. I had been looking to cancel it somehow too.

**Pull request closed without merging**
